INSERT INTO son (id,  apgar1,  apgar10,  apgar5,  asphyxiadelivery,  attachedtime,  bcg,  bornalive,  consistency,  cry,  extremepremature,  gas,  mechanicalventilation, name, of,  og,  ot,  pediatricexamination,  secretion,  secretioncolour, size,  skullperimeter,  tempaxilar,  temprectal,  ticket,  vitk,  weight,  weightplacenta,  delivery_id,  gender_id,  mother_id,  year_id,  profile_id)
VALUES (2,  '4',  '5',  '5', FALSE,  '12', FALSE, TRUE,  'No', FALSE, TRUE, FALSE, FALSE,  'Joffrey Lannister', FALSE, FALSE, FALSE, 30,  'No',  'No',  '34',  '23',  '33',  '34', 11, FALSE,  '1433',  '10', 2, 1, 2, 2010, 52);
INSERT INTO son (id,  apgar1,  apgar10,  apgar5,  asphyxiadelivery,  attachedtime,  bcg,  bornalive,  consistency,  cry,  extremepremature,  gas,  mechanicalventilation, name, of,  og,  ot,  pediatricexamination,  secretion,  secretioncolour, size,  skullperimeter,  tempaxilar,  temprectal,  ticket,  vitk,  weight,  weightplacenta,  delivery_id,  gender_id,  mother_id,  year_id,  profile_id)
VALUES (3,  '4',  '5',  '5', TRUE,  '12', TRUE, TRUE,  'No', TRUE, FALSE, TRUE, TRUE,  'Joffrey Lannister', TRUE, TRUE, TRUE, 31,  'No',  'No',  '34',  '23',  '33',  '34', 12, TRUE,  '1566',  '10', 2, 2, 3, 2011, 53);
INSERT INTO son (id,  apgar1,  apgar10,  apgar5,  asphyxiadelivery,  attachedtime,  bcg,  bornalive,  consistency,  cry,  extremepremature,  gas,  mechanicalventilation, name, of,  og,  ot,  pediatricexamination,  secretion,  secretioncolour, size,  skullperimeter,  tempaxilar,  temprectal,  ticket,  vitk,  weight,  weightplacenta,  delivery_id,  gender_id,  mother_id,  year_id,  profile_id)
VALUES (4,  '4',  '5',  '5', TRUE,  '12', TRUE, TRUE,  'No', TRUE, FALSE, TRUE, TRUE,  'Joffrey Lannister', TRUE, TRUE, TRUE, 32,  'No',  'No',  '34',  '23',  '33',  '34', 13, FALSE,  '1566',  '10', 3, 1, 4, 2012, 54);
INSERT INTO son (id,  apgar1,  apgar10,  apgar5,  asphyxiadelivery,  attachedtime,  bcg,  bornalive,  consistency,  cry,  extremepremature,  gas,  mechanicalventilation, name, of,  og,  ot,  pediatricexamination,  secretion,  secretioncolour, size,  skullperimeter,  tempaxilar,  temprectal,  ticket,  vitk,  weight,  weightplacenta,  delivery_id,  gender_id,  mother_id,  year_id,  profile_id)
VALUES (5,  '4',  '5',  '5', TRUE,  '12', TRUE, TRUE,  'No', TRUE, FALSE, TRUE, TRUE,  'Joffrey Lannister', TRUE, TRUE, TRUE, 33,  'No',  'No',  '34',  '23',  '33',  '34', 14, TRUE,  '1566',  '10', 4, 2, 5, 2013, 55);
INSERT INTO son (id,  apgar1,  apgar10,  apgar5,  asphyxiadelivery,  attachedtime,  bcg,  bornalive,  consistency,  cry,  extremepremature,  gas,  mechanicalventilation, name, of,  og,  ot,  pediatricexamination,  secretion,  secretioncolour, size,  skullperimeter,  tempaxilar,  temprectal,  ticket,  vitk,  weight,  weightplacenta,  delivery_id,  gender_id,  mother_id,  year_id,  profile_id)
VALUES (6,  '4',  '5',  '5', TRUE,  '12', TRUE, TRUE,  'No', TRUE, FALSE, TRUE, TRUE,  'Joffrey Lannister', TRUE, TRUE, TRUE, 34,  'No',  'No',  '34',  '23',  '33',  '34', 15, TRUE,  '1566',  '10', 5, 1, 6, 2014, 56);
INSERT INTO son (id,  apgar1,  apgar10,  apgar5,  asphyxiadelivery,  attachedtime,  bcg,  bornalive,  consistency,  cry,  extremepremature,  gas,  mechanicalventilation, name, of,  og,  ot,  pediatricexamination,  secretion,  secretioncolour, size,  skullperimeter,  tempaxilar,  temprectal,  ticket,  vitk,  weight,  weightplacenta,  delivery_id,  gender_id,  mother_id,  year_id,  profile_id)
VALUES (7,  '4',  '5',  '5', TRUE,  '12', TRUE, TRUE,  'No', TRUE, FALSE, TRUE, TRUE,  'Joffrey Lannister', TRUE, TRUE, TRUE, 35,  'No',  'No',  '34',  '23',  '33',  '34', 16, TRUE,  '1566',  '10', 6, 2, 7, 2010, 57);
INSERT INTO son (id,  apgar1,  apgar10,  apgar5,  asphyxiadelivery,  attachedtime,  bcg,  bornalive,  consistency,  cry,  extremepremature,  gas,  mechanicalventilation, name, of,  og,  ot,  pediatricexamination,  secretion,  secretioncolour, size,  skullperimeter,  tempaxilar,  temprectal,  ticket,  vitk,  weight,  weightplacenta,  delivery_id,  gender_id,  mother_id,  year_id,  profile_id)
VALUES (8,  '4',  '5',  '5', TRUE,  '12', TRUE, TRUE,  'No', TRUE, FALSE, TRUE, TRUE,  'Joffrey Lannister', TRUE, TRUE, TRUE, 36,  'No',  'No',  '34',  '23',  '33',  '34', 17, FALSE,  '1566',  '10', 7, 1, 8, 2011, 58);
INSERT INTO son (id,  apgar1,  apgar10,  apgar5,  asphyxiadelivery,  attachedtime,  bcg,  bornalive,  consistency,  cry,  extremepremature,  gas,  mechanicalventilation, name, of,  og,  ot,  pediatricexamination,  secretion,  secretioncolour, size,  skullperimeter,  tempaxilar,  temprectal,  ticket,  vitk,  weight,  weightplacenta,  delivery_id,  gender_id,  mother_id,  year_id,  profile_id)
VALUES (9,  '4',  '5',  '5', TRUE,  '12', TRUE, TRUE,  'No', TRUE, FALSE, TRUE, TRUE,  'Joffrey Lannister', TRUE, TRUE, TRUE, 37,  'No',  'No',  '34',  '23',  '33',  '34', 18, TRUE,  '1566',  '10', 8, 2, 9, 2012, 59);
INSERT INTO son (id,  apgar1,  apgar10,  apgar5,  asphyxiadelivery,  attachedtime,  bcg,  bornalive,  consistency,  cry,  extremepremature,  gas,  mechanicalventilation, name, of,  og,  ot,  pediatricexamination,  secretion,  secretioncolour, size,  skullperimeter,  tempaxilar,  temprectal,  ticket,  vitk,  weight,  weightplacenta,  delivery_id,  gender_id,  mother_id,  year_id,  profile_id)
VALUES (10,  '4',  '5',  '5', TRUE,  '12', TRUE, TRUE,  'No', TRUE, TRUE, TRUE, TRUE,  'Joffrey Lannister', TRUE, TRUE, TRUE, 30,  'No',  'No',  '34',  '23',  '33',  '34', 19, FALSE,  '1344',  '10', 9, 1, 10, 2013, 60);
INSERT INTO son (id,  apgar1,  apgar10,  apgar5,  asphyxiadelivery,  attachedtime,  bcg,  bornalive,  consistency,  cry,  extremepremature,  gas,  mechanicalventilation, name, of,  og,  ot,  pediatricexamination,  secretion,  secretioncolour, size,  skullperimeter,  tempaxilar,  temprectal,  ticket,  vitk,  weight,  weightplacenta,  delivery_id,  gender_id,  mother_id,  year_id,  profile_id)
VALUES (11,  '4',  '5',  '5', TRUE,  '12', TRUE, TRUE,  'No', TRUE, FALSE, TRUE, TRUE,  'Joffrey Lannister', TRUE, TRUE, TRUE, 31,  'No',  'No',  '34',  '23',  '33',  '34', 20, TRUE,  '1566',  '10', 10, 2, 11, 2014, 61);
INSERT INTO son (id,  apgar1,  apgar10,  apgar5,  asphyxiadelivery,  attachedtime,  bcg,  bornalive,  consistency,  cry,  extremepremature,  gas,  mechanicalventilation, name, of,  og,  ot,  pediatricexamination,  secretion,  secretioncolour, size,  skullperimeter,  tempaxilar,  temprectal,  ticket,  vitk,  weight,  weightplacenta,  delivery_id,  gender_id,  mother_id,  year_id,  profile_id)
VALUES (12,  '4',  '5',  '5', TRUE,  '12', TRUE, TRUE,  'No', TRUE, FALSE, TRUE, TRUE,  'Joffrey Lannister', TRUE, TRUE, TRUE, 32,  'No',  'No',  '34',  '23',  '33',  '34', 21, TRUE,  '1566',  '10', 11, 1, 12, 2010, 62);
INSERT INTO son (id,  apgar1,  apgar10,  apgar5,  asphyxiadelivery,  attachedtime,  bcg,  bornalive,  consistency,  cry,  extremepremature,  gas,  mechanicalventilation, name, of,  og,  ot,  pediatricexamination,  secretion,  secretioncolour, size,  skullperimeter,  tempaxilar,  temprectal,  ticket,  vitk,  weight,  weightplacenta,  delivery_id,  gender_id,  mother_id,  year_id,  profile_id)
VALUES (13,  '4',  '5',  '5', TRUE,  '12', TRUE, TRUE,  'No', TRUE, FALSE, TRUE, TRUE,  'Joffrey Lannister', TRUE, TRUE, TRUE, 33,  'No',  'No',  '34',  '23',  '33',  '34', 22, TRUE,  '1566',  '10', 12, 2, 13, 2011, 63);
INSERT INTO son (id,  apgar1,  apgar10,  apgar5,  asphyxiadelivery,  attachedtime,  bcg,  bornalive,  consistency,  cry,  extremepremature,  gas,  mechanicalventilation, name, of,  og,  ot,  pediatricexamination,  secretion,  secretioncolour, size,  skullperimeter,  tempaxilar,  temprectal,  ticket,  vitk,  weight,  weightplacenta,  delivery_id,  gender_id,  mother_id,  year_id,  profile_id)
VALUES (14,  '4',  '5',  '5', TRUE,  '12', TRUE, TRUE,  'No', TRUE, FALSE, TRUE, TRUE,  'Joffrey Lannister', TRUE, TRUE, TRUE, 34,  'No',  'No',  '34',  '23',  '33',  '34', 23, TRUE,  '1566',  '10', 13, 1, 14, 2012, 64);
INSERT INTO son (id,  apgar1,  apgar10,  apgar5,  asphyxiadelivery,  attachedtime,  bcg,  bornalive,  consistency,  cry,  extremepremature,  gas,  mechanicalventilation, name, of,  og,  ot,  pediatricexamination,  secretion,  secretioncolour, size,  skullperimeter,  tempaxilar,  temprectal,  ticket,  vitk,  weight,  weightplacenta,  delivery_id,  gender_id,  mother_id,  year_id,  profile_id)
VALUES (15,  '4',  '5',  '5', TRUE,  '12', TRUE, TRUE,  'No', TRUE, FALSE, TRUE, TRUE,  'Joffrey Lannister', TRUE, TRUE, TRUE, 35,  'No',  'No',  '34',  '23',  '33',  '34', 24, TRUE,  '1566',  '10', 14, 2, 15, 2013, 65);
INSERT INTO son (id,  apgar1,  apgar10,  apgar5,  asphyxiadelivery,  attachedtime,  bcg,  bornalive,  consistency,  cry,  extremepremature,  gas,  mechanicalventilation, name, of,  og,  ot,  pediatricexamination,  secretion,  secretioncolour, size,  skullperimeter,  tempaxilar,  temprectal,  ticket,  vitk,  weight,  weightplacenta,  delivery_id,  gender_id,  mother_id,  year_id,  profile_id)
VALUES (16,  '4',  '5',  '5', TRUE,  '12', TRUE, TRUE,  'No', TRUE, FALSE, TRUE, TRUE,  'Joffrey Lannister', TRUE, TRUE, TRUE, 36,  'No',  'No',  '34',  '23',  '33',  '34', 25, TRUE,  '1566',  '10', 15, 1, 16, 2014, 66);
INSERT INTO son (id,  apgar1,  apgar10,  apgar5,  asphyxiadelivery,  attachedtime,  bcg,  bornalive,  consistency,  cry,  extremepremature,  gas,  mechanicalventilation, name, of,  og,  ot,  pediatricexamination,  secretion,  secretioncolour, size,  skullperimeter,  tempaxilar,  temprectal,  ticket,  vitk,  weight,  weightplacenta,  delivery_id,  gender_id,  mother_id,  year_id,  profile_id)
VALUES (17,  '4',  '5',  '5', TRUE,  '12', TRUE, TRUE,  'No', TRUE, FALSE, TRUE, TRUE,  'Joffrey Lannister', TRUE, TRUE, TRUE, 37,  'No',  'No',  '34',  '23',  '33',  '34', 26, TRUE,  '1566',  '10', 16, 2, 17, 2010, 67);
INSERT INTO son (id,  apgar1,  apgar10,  apgar5,  asphyxiadelivery,  attachedtime,  bcg,  bornalive,  consistency,  cry,  extremepremature,  gas,  mechanicalventilation, name, of,  og,  ot,  pediatricexamination,  secretion,  secretioncolour, size,  skullperimeter,  tempaxilar,  temprectal,  ticket,  vitk,  weight,  weightplacenta,  delivery_id,  gender_id,  mother_id,  year_id,  profile_id)
VALUES (18,  '4',  '5',  '5', TRUE,  '12', TRUE, TRUE,  'No', TRUE, TRUE, TRUE, TRUE,  'Joffrey Lannister', TRUE, TRUE, TRUE, 30,  'No',  'No',  '34',  '23',  '33',  '34', 27, TRUE,  '1463',  '10', 17, 1, 18, 2011, 68);
INSERT INTO son (id,  apgar1,  apgar10,  apgar5,  asphyxiadelivery,  attachedtime,  bcg,  bornalive,  consistency,  cry,  extremepremature,  gas,  mechanicalventilation, name, of,  og,  ot,  pediatricexamination,  secretion,  secretioncolour, size,  skullperimeter,  tempaxilar,  temprectal,  ticket,  vitk,  weight,  weightplacenta,  delivery_id,  gender_id,  mother_id,  year_id,  profile_id)
VALUES (19,  '4',  '5',  '5', TRUE,  '12', TRUE, TRUE,  'No', TRUE, FALSE, TRUE, TRUE,  'Joffrey Lannister', TRUE, TRUE, TRUE, 31,  'No',  'No',  '34',  '23',  '33',  '34', 28, TRUE,  '1566',  '10', 18, 2, 19, 2012, 69);
INSERT INTO son (id,  apgar1,  apgar10,  apgar5,  asphyxiadelivery,  attachedtime,  bcg,  bornalive,  consistency,  cry,  extremepremature,  gas,  mechanicalventilation, name, of,  og,  ot,  pediatricexamination,  secretion,  secretioncolour, size,  skullperimeter,  tempaxilar,  temprectal,  ticket,  vitk,  weight,  weightplacenta,  delivery_id,  gender_id,  mother_id,  year_id,  profile_id)
VALUES (20,  '4',  '5',  '5', TRUE,  '12', TRUE, TRUE,  'No', TRUE, FALSE, TRUE, TRUE,  'Joffrey Lannister', TRUE, TRUE, TRUE, 32,  'No',  'No',  '34',  '23',  '33',  '34', 29, TRUE,  '1566',  '10', 19, 1, 20, 2013, 70);
INSERT INTO son (id,  apgar1,  apgar10,  apgar5,  asphyxiadelivery,  attachedtime,  bcg,  bornalive,  consistency,  cry,  extremepremature,  gas,  mechanicalventilation, name, of,  og,  ot,  pediatricexamination,  secretion,  secretioncolour, size,  skullperimeter,  tempaxilar,  temprectal,  ticket,  vitk,  weight,  weightplacenta,  delivery_id,  gender_id,  mother_id,  year_id,  profile_id)
VALUES (21,  '4',  '5',  '5', TRUE,  '12', TRUE, TRUE,  'No', TRUE, FALSE, TRUE, TRUE,  'Joffrey Lannister', TRUE, TRUE, TRUE, 33,  'No',  'No',  '34',  '23',  '33',  '34', 30, TRUE,  '1566',  '10', 20, 2, 21, 2014, 71);
INSERT INTO son (id,  apgar1,  apgar10,  apgar5,  asphyxiadelivery,  attachedtime,  bcg,  bornalive,  consistency,  cry,  extremepremature,  gas,  mechanicalventilation, name, of,  og,  ot,  pediatricexamination,  secretion,  secretioncolour, size,  skullperimeter,  tempaxilar,  temprectal,  ticket,  vitk,  weight,  weightplacenta,  delivery_id,  gender_id,  mother_id,  year_id,  profile_id)
VALUES (22,  '4',  '5',  '5', TRUE,  '12', TRUE, TRUE,  'No', TRUE, FALSE, TRUE, TRUE,  'Joffrey Lannister', TRUE, TRUE, TRUE, 34,  'No',  'No',  '34',  '23',  '33',  '34', 31, TRUE,  '1566',  '10', 21, 1, 22, 2010, 72);
INSERT INTO son (id,  apgar1,  apgar10,  apgar5,  asphyxiadelivery,  attachedtime,  bcg,  bornalive,  consistency,  cry,  extremepremature,  gas,  mechanicalventilation, name, of,  og,  ot,  pediatricexamination,  secretion,  secretioncolour, size,  skullperimeter,  tempaxilar,  temprectal,  ticket,  vitk,  weight,  weightplacenta,  delivery_id,  gender_id,  mother_id,  year_id,  profile_id)
VALUES (23,  '4',  '5',  '5', TRUE,  '12', TRUE, TRUE,  'No', TRUE, FALSE, TRUE, TRUE,  'Joffrey Lannister', TRUE, TRUE, TRUE, 35,  'No',  'No',  '34',  '23',  '33',  '34', 32, TRUE,  '1566',  '10', 22, 2, 23, 2011, 73);
INSERT INTO son (id,  apgar1,  apgar10,  apgar5,  asphyxiadelivery,  attachedtime,  bcg,  bornalive,  consistency,  cry,  extremepremature,  gas,  mechanicalventilation, name, of,  og,  ot,  pediatricexamination,  secretion,  secretioncolour, size,  skullperimeter,  tempaxilar,  temprectal,  ticket,  vitk,  weight,  weightplacenta,  delivery_id,  gender_id,  mother_id,  year_id,  profile_id)
VALUES (24,  '4',  '5',  '5', TRUE,  '12', TRUE, TRUE,  'No', TRUE, FALSE, TRUE, TRUE,  'Joffrey Lannister', TRUE, TRUE, TRUE, 36,  'No',  'No',  '34',  '23',  '33',  '34', 33, TRUE,  '1566',  '10', 23, 1, 24, 2012, 74);
INSERT INTO son (id,  apgar1,  apgar10,  apgar5,  asphyxiadelivery,  attachedtime,  bcg,  bornalive,  consistency,  cry,  extremepremature,  gas,  mechanicalventilation, name, of,  og,  ot,  pediatricexamination,  secretion,  secretioncolour, size,  skullperimeter,  tempaxilar,  temprectal,  ticket,  vitk,  weight,  weightplacenta,  delivery_id,  gender_id,  mother_id,  year_id,  profile_id)
VALUES (25,  '4',  '5',  '5', TRUE,  '12', TRUE, TRUE,  'No', TRUE, FALSE, TRUE, TRUE,  'Joffrey Lannister', TRUE, TRUE, TRUE, 37,  'No',  'No',  '34',  '23',  '33',  '34', 34, TRUE,  '1566',  '10', 24, 2, 25, 2013, 75);
INSERT INTO son (id,  apgar1,  apgar10,  apgar5,  asphyxiadelivery,  attachedtime,  bcg,  bornalive,  consistency,  cry,  extremepremature,  gas,  mechanicalventilation, name, of,  og,  ot,  pediatricexamination,  secretion,  secretioncolour, size,  skullperimeter,  tempaxilar,  temprectal,  ticket,  vitk,  weight,  weightplacenta,  delivery_id,  gender_id,  mother_id,  year_id,  profile_id)
VALUES (26,  '4',  '5',  '5', TRUE,  '12', TRUE, TRUE,  'No', TRUE, TRUE, TRUE, TRUE,  'Joffrey Lannister', TRUE, TRUE, TRUE, 30,  'No',  'No',  '34',  '23',  '33',  '34', 35, TRUE,  '1347',  '10', 25, 1, 26, 2014, 76);
INSERT INTO son (id,  apgar1,  apgar10,  apgar5,  asphyxiadelivery,  attachedtime,  bcg,  bornalive,  consistency,  cry,  extremepremature,  gas,  mechanicalventilation, name, of,  og,  ot,  pediatricexamination,  secretion,  secretioncolour, size,  skullperimeter,  tempaxilar,  temprectal,  ticket,  vitk,  weight,  weightplacenta,  delivery_id,  gender_id,  mother_id,  year_id,  profile_id)
VALUES (27,  '4',  '5',  '5', TRUE,  '12', TRUE, TRUE,  'No', TRUE, FALSE, TRUE, TRUE,  'Joffrey Lannister', TRUE, TRUE, TRUE, 31,  'No',  'No',  '34',  '23',  '33',  '34', 36, TRUE,  '1566',  '10', 26, 2, 27, 2010, 77);
INSERT INTO son (id,  apgar1,  apgar10,  apgar5,  asphyxiadelivery,  attachedtime,  bcg,  bornalive,  consistency,  cry,  extremepremature,  gas,  mechanicalventilation, name, of,  og,  ot,  pediatricexamination,  secretion,  secretioncolour, size,  skullperimeter,  tempaxilar,  temprectal,  ticket,  vitk,  weight,  weightplacenta,  delivery_id,  gender_id,  mother_id,  year_id,  profile_id)
VALUES (28,  '4',  '5',  '5', TRUE,  '12', TRUE, TRUE,  'No', TRUE, FALSE, TRUE, TRUE,  'Joffrey Lannister', TRUE, TRUE, TRUE, 32,  'No',  'No',  '34',  '23',  '33',  '34', 37, TRUE,  '1566',  '10', 27, 1, 28, 2011, 78);
INSERT INTO son (id,  apgar1,  apgar10,  apgar5,  asphyxiadelivery,  attachedtime,  bcg,  bornalive,  consistency,  cry,  extremepremature,  gas,  mechanicalventilation, name, of,  og,  ot,  pediatricexamination,  secretion,  secretioncolour, size,  skullperimeter,  tempaxilar,  temprectal,  ticket,  vitk,  weight,  weightplacenta,  delivery_id,  gender_id,  mother_id,  year_id,  profile_id)
VALUES (29,  '4',  '5',  '5', TRUE,  '12', TRUE, TRUE,  'No', TRUE, FALSE, TRUE, TRUE,  'Joffrey Lannister', TRUE, TRUE, TRUE, 33,  'No',  'No',  '34',  '23',  '33',  '34', 38, TRUE,  '1566',  '10', 28, 2, 29, 2012, 79);
INSERT INTO son (id,  apgar1,  apgar10,  apgar5,  asphyxiadelivery,  attachedtime,  bcg,  bornalive,  consistency,  cry,  extremepremature,  gas,  mechanicalventilation, name, of,  og,  ot,  pediatricexamination,  secretion,  secretioncolour, size,  skullperimeter,  tempaxilar,  temprectal,  ticket,  vitk,  weight,  weightplacenta,  delivery_id,  gender_id,  mother_id,  year_id,  profile_id)
VALUES (30,  '4',  '5',  '5', TRUE,  '12', TRUE, TRUE,  'No', TRUE, FALSE, TRUE, TRUE,  'Joffrey Lannister', TRUE, TRUE, TRUE, 34,  'No',  'No',  '34',  '23',  '33',  '34', 39, TRUE,  '1566',  '10', 29, 1, 30, 2013, 80);
INSERT INTO son (id,  apgar1,  apgar10,  apgar5,  asphyxiadelivery,  attachedtime,  bcg,  bornalive,  consistency,  cry,  extremepremature,  gas,  mechanicalventilation, name, of,  og,  ot,  pediatricexamination,  secretion,  secretioncolour, size,  skullperimeter,  tempaxilar,  temprectal,  ticket,  vitk,  weight,  weightplacenta,  delivery_id,  gender_id,  mother_id,  year_id,  profile_id)
VALUES (31,  '4',  '5',  '5', TRUE,  '12', TRUE, TRUE,  'No', TRUE, FALSE, TRUE, TRUE,  'Joffrey Lannister', TRUE, TRUE, TRUE, 35,  'No',  'No',  '34',  '23',  '33',  '34', 40, TRUE,  '1566',  '10', 30, 2, 31, 2014, 81);
INSERT INTO son (id,  apgar1,  apgar10,  apgar5,  asphyxiadelivery,  attachedtime,  bcg,  bornalive,  consistency,  cry,  extremepremature,  gas,  mechanicalventilation, name, of,  og,  ot,  pediatricexamination,  secretion,  secretioncolour, size,  skullperimeter,  tempaxilar,  temprectal,  ticket,  vitk,  weight,  weightplacenta,  delivery_id,  gender_id,  mother_id,  year_id,  profile_id)
VALUES (32,  '4',  '5',  '5', TRUE,  '12', TRUE, TRUE,  'No', TRUE, FALSE, TRUE, TRUE,  'Joffrey Lannister', TRUE, TRUE, TRUE, 36,  'No',  'No',  '34',  '23',  '33',  '34', 41, TRUE,  '1566',  '10', 31, 1, 32, 2010, 82);
INSERT INTO son (id,  apgar1,  apgar10,  apgar5,  asphyxiadelivery,  attachedtime,  bcg,  bornalive,  consistency,  cry,  extremepremature,  gas,  mechanicalventilation, name, of,  og,  ot,  pediatricexamination,  secretion,  secretioncolour, size,  skullperimeter,  tempaxilar,  temprectal,  ticket,  vitk,  weight,  weightplacenta,  delivery_id,  gender_id,  mother_id,  year_id,  profile_id)
VALUES (33,  '4',  '5',  '5', TRUE,  '12', TRUE, TRUE,  'No', TRUE, FALSE, TRUE, TRUE,  'Joffrey Lannister', TRUE, TRUE, TRUE, 37,  'No',  'No',  '34',  '23',  '33',  '34', 42, TRUE,  '1566',  '10', 32, 2, 33, 2011, 83);
INSERT INTO son (id,  apgar1,  apgar10,  apgar5,  asphyxiadelivery,  attachedtime,  bcg,  bornalive,  consistency,  cry,  extremepremature,  gas,  mechanicalventilation, name, of,  og,  ot,  pediatricexamination,  secretion,  secretioncolour, size,  skullperimeter,  tempaxilar,  temprectal,  ticket,  vitk,  weight,  weightplacenta,  delivery_id,  gender_id,  mother_id,  year_id,  profile_id)
VALUES (34,  '4',  '5',  '5', TRUE,  '12', TRUE, TRUE,  'No', TRUE, TRUE, TRUE, TRUE,  'Joffrey Lannister', TRUE, TRUE, TRUE, 30,  'No',  'No',  '34',  '23',  '33',  '34', 43, TRUE,  '1245',  '10', 33, 1, 34, 2012, 84);
INSERT INTO son (id,  apgar1,  apgar10,  apgar5,  asphyxiadelivery,  attachedtime,  bcg,  bornalive,  consistency,  cry,  extremepremature,  gas,  mechanicalventilation, name, of,  og,  ot,  pediatricexamination,  secretion,  secretioncolour, size,  skullperimeter,  tempaxilar,  temprectal,  ticket,  vitk,  weight,  weightplacenta,  delivery_id,  gender_id,  mother_id,  year_id,  profile_id)
VALUES (35,  '4',  '5',  '5', TRUE,  '12', TRUE, TRUE,  'No', TRUE, FALSE, TRUE, TRUE,  'Joffrey Lannister', TRUE, TRUE, TRUE, 31,  'No',  'No',  '34',  '23',  '33',  '34', 44, TRUE,  '1866',  '10', 34, 2, 35, 2013, 85);
INSERT INTO son (id,  apgar1,  apgar10,  apgar5,  asphyxiadelivery,  attachedtime,  bcg,  bornalive,  consistency,  cry,  extremepremature,  gas,  mechanicalventilation, name, of,  og,  ot,  pediatricexamination,  secretion,  secretioncolour, size,  skullperimeter,  tempaxilar,  temprectal,  ticket,  vitk,  weight,  weightplacenta,  delivery_id,  gender_id,  mother_id,  year_id,  profile_id)
VALUES (36,  '4',  '5',  '5', TRUE,  '12', TRUE, TRUE,  'No', TRUE, FALSE, TRUE, TRUE,  'Joffrey Lannister', TRUE, TRUE, TRUE, 32,  'No',  'No',  '34',  '23',  '33',  '34', 45, TRUE,  '1866',  '10', 35, 1, 36, 2014, 86);
INSERT INTO son (id,  apgar1,  apgar10,  apgar5,  asphyxiadelivery,  attachedtime,  bcg,  bornalive,  consistency,  cry,  extremepremature,  gas,  mechanicalventilation, name, of,  og,  ot,  pediatricexamination,  secretion,  secretioncolour, size,  skullperimeter,  tempaxilar,  temprectal,  ticket,  vitk,  weight,  weightplacenta,  delivery_id,  gender_id,  mother_id,  year_id,  profile_id)
VALUES (37,  '4',  '5',  '5', TRUE,  '12', TRUE, TRUE,  'No', TRUE, FALSE, TRUE, TRUE,  'Joffrey Lannister', TRUE, TRUE, TRUE, 33,  'No',  'No',  '34',  '23',  '33',  '34', 46, TRUE,  '1866',  '10', 36, 2, 37, 2010, 87);
INSERT INTO son (id,  apgar1,  apgar10,  apgar5,  asphyxiadelivery,  attachedtime,  bcg,  bornalive,  consistency,  cry,  extremepremature,  gas,  mechanicalventilation, name, of,  og,  ot,  pediatricexamination,  secretion,  secretioncolour, size,  skullperimeter,  tempaxilar,  temprectal,  ticket,  vitk,  weight,  weightplacenta,  delivery_id,  gender_id,  mother_id,  year_id,  profile_id)
VALUES (38,  '4',  '5',  '5', TRUE,  '12', TRUE, TRUE,  'No', TRUE, FALSE, TRUE, TRUE,  'Joffrey Lannister', TRUE, TRUE, TRUE, 34,  'No',  'No',  '34',  '23',  '33',  '34', 47, TRUE,  '1866',  '10', 37, 1, 38, 2011, 88);
INSERT INTO son (id,  apgar1,  apgar10,  apgar5,  asphyxiadelivery,  attachedtime,  bcg,  bornalive,  consistency,  cry,  extremepremature,  gas,  mechanicalventilation, name, of,  og,  ot,  pediatricexamination,  secretion,  secretioncolour, size,  skullperimeter,  tempaxilar,  temprectal,  ticket,  vitk,  weight,  weightplacenta,  delivery_id,  gender_id,  mother_id,  year_id,  profile_id)
VALUES (39,  '4',  '5',  '5', TRUE,  '12', TRUE, TRUE,  'No', TRUE, FALSE, TRUE, TRUE,  'Joffrey Lannister', TRUE, TRUE, TRUE, 35,  'No',  'No',  '34',  '23',  '33',  '34', 48, TRUE,  '2923',  '10', 38, 2, 39, 2012, 89);
INSERT INTO son (id,  apgar1,  apgar10,  apgar5,  asphyxiadelivery,  attachedtime,  bcg,  bornalive,  consistency,  cry,  extremepremature,  gas,  mechanicalventilation, name, of,  og,  ot,  pediatricexamination,  secretion,  secretioncolour, size,  skullperimeter,  tempaxilar,  temprectal,  ticket,  vitk,  weight,  weightplacenta,  delivery_id,  gender_id,  mother_id,  year_id,  profile_id)
VALUES (40,  '4',  '5',  '5', TRUE,  '12', TRUE, TRUE,  'No', TRUE, FALSE, TRUE, TRUE,  'Joffrey Lannister', TRUE, TRUE, TRUE, 36,  'No',  'No',  '34',  '23',  '33',  '34', 49, TRUE,  '2923',  '10', 39, 1, 40, 2013, 90);
INSERT INTO son (id,  apgar1,  apgar10,  apgar5,  asphyxiadelivery,  attachedtime,  bcg,  bornalive,  consistency,  cry,  extremepremature,  gas,  mechanicalventilation, name, of,  og,  ot,  pediatricexamination,  secretion,  secretioncolour, size,  skullperimeter,  tempaxilar,  temprectal,  ticket,  vitk,  weight,  weightplacenta,  delivery_id,  gender_id,  mother_id,  year_id,  profile_id)
VALUES (41,  '4',  '5',  '5', TRUE,  '12', TRUE, TRUE,  'No', TRUE, FALSE, TRUE, TRUE,  'Joffrey Lannister', TRUE, TRUE, TRUE, 37,  'No',  'No',  '34',  '23',  '33',  '34', 50, TRUE,  '2923',  '10', 40, 2, 41, 2014, 91);
INSERT INTO son (id,  apgar1,  apgar10,  apgar5,  asphyxiadelivery,  attachedtime,  bcg,  bornalive,  consistency,  cry,  extremepremature,  gas,  mechanicalventilation, name, of,  og,  ot,  pediatricexamination,  secretion,  secretioncolour, size,  skullperimeter,  tempaxilar,  temprectal,  ticket,  vitk,  weight,  weightplacenta,  delivery_id,  gender_id,  mother_id,  year_id,  profile_id)
VALUES (42,  '4',  '5',  '5', TRUE,  '12', TRUE, TRUE,  'No', TRUE, TRUE, TRUE, TRUE,  'Joffrey Lannister', TRUE, TRUE, TRUE, 30,  'No',  'No',  '34',  '23',  '33',  '34', 51, TRUE,  '2923',  '10', 41, 1, 42, 2010, 92);
INSERT INTO son (id,  apgar1,  apgar10,  apgar5,  asphyxiadelivery,  attachedtime,  bcg,  bornalive,  consistency,  cry,  extremepremature,  gas,  mechanicalventilation, name, of,  og,  ot,  pediatricexamination,  secretion,  secretioncolour, size,  skullperimeter,  tempaxilar,  temprectal,  ticket,  vitk,  weight,  weightplacenta,  delivery_id,  gender_id,  mother_id,  year_id,  profile_id)
VALUES (43,  '4',  '5',  '5', TRUE,  '12', TRUE, TRUE,  'No', TRUE, FALSE, TRUE, TRUE,  'Joffrey Lannister', TRUE, TRUE, TRUE, 31,  'No',  'No',  '34',  '23',  '33',  '34', 52, TRUE,  '2223',  '10', 42, 2, 43, 2011, 93);
INSERT INTO son (id,  apgar1,  apgar10,  apgar5,  asphyxiadelivery,  attachedtime,  bcg,  bornalive,  consistency,  cry,  extremepremature,  gas,  mechanicalventilation, name, of,  og,  ot,  pediatricexamination,  secretion,  secretioncolour, size,  skullperimeter,  tempaxilar,  temprectal,  ticket,  vitk,  weight,  weightplacenta,  delivery_id,  gender_id,  mother_id,  year_id,  profile_id)
VALUES (44,  '4',  '5',  '5', TRUE,  '12', TRUE, TRUE,  'No', TRUE, FALSE, TRUE, TRUE,  'Joffrey Lannister', TRUE, TRUE, TRUE, 32,  'No',  'No',  '34',  '23',  '33',  '34', 53, TRUE,  '2223',  '10', 43, 1, 44, 2012, 94);
INSERT INTO son (id,  apgar1,  apgar10,  apgar5,  asphyxiadelivery,  attachedtime,  bcg,  bornalive,  consistency,  cry,  extremepremature,  gas,  mechanicalventilation, name, of,  og,  ot,  pediatricexamination,  secretion,  secretioncolour, size,  skullperimeter,  tempaxilar,  temprectal,  ticket,  vitk,  weight,  weightplacenta,  delivery_id,  gender_id,  mother_id,  year_id,  profile_id)
VALUES (45,  '4',  '5',  '5', TRUE,  '12', TRUE, TRUE,  'No', TRUE, FALSE, TRUE, TRUE,  'Joffrey Lannister', TRUE, TRUE, TRUE, 33,  'No',  'No',  '34',  '23',  '33',  '34', 54, TRUE,  '2223',  '10', 44, 2, 45, 2013, 95);
INSERT INTO son (id,  apgar1,  apgar10,  apgar5,  asphyxiadelivery,  attachedtime,  bcg,  bornalive,  consistency,  cry,  extremepremature,  gas,  mechanicalventilation, name, of,  og,  ot,  pediatricexamination,  secretion,  secretioncolour, size,  skullperimeter,  tempaxilar,  temprectal,  ticket,  vitk,  weight,  weightplacenta,  delivery_id,  gender_id,  mother_id,  year_id,  profile_id)
VALUES (46,  '4',  '5',  '5', TRUE,  '12', TRUE, TRUE,  'No', TRUE, FALSE, TRUE, TRUE,  'Joffrey Lannister', TRUE, TRUE, TRUE, 34,  'No',  'No',  '34',  '23',  '33',  '34', 55, TRUE,  '2223',  '10', 45, 1, 46, 2014, 96);
INSERT INTO son (id,  apgar1,  apgar10,  apgar5,  asphyxiadelivery,  attachedtime,  bcg,  bornalive,  consistency,  cry,  extremepremature,  gas,  mechanicalventilation, name, of,  og,  ot,  pediatricexamination,  secretion,  secretioncolour, size,  skullperimeter,  tempaxilar,  temprectal,  ticket,  vitk,  weight,  weightplacenta,  delivery_id,  gender_id,  mother_id,  year_id,  profile_id)
VALUES (47,  '4',  '5',  '5', TRUE,  '12', TRUE, TRUE,  'No', TRUE, FALSE, TRUE, TRUE,  'Joffrey Lannister', TRUE, TRUE, TRUE, 35,  'No',  'No',  '34',  '23',  '33',  '34', 56, TRUE,  '2223',  '10', 46, 2, 47, 2010, 97);
INSERT INTO son (id,  apgar1,  apgar10,  apgar5,  asphyxiadelivery,  attachedtime,  bcg,  bornalive,  consistency,  cry,  extremepremature,  gas,  mechanicalventilation, name, of,  og,  ot,  pediatricexamination,  secretion,  secretioncolour, size,  skullperimeter,  tempaxilar,  temprectal,  ticket,  vitk,  weight,  weightplacenta,  delivery_id,  gender_id,  mother_id,  year_id,  profile_id)
VALUES (48,  '4',  '5',  '5', TRUE,  '12', TRUE, TRUE,  'No', TRUE, FALSE, TRUE, TRUE,  'Joffrey Lannister', TRUE, TRUE, TRUE, 36,  'No',  'No',  '34',  '23',  '33',  '34', 57, TRUE,  '2223',  '10', 47, 1, 48, 2011, 98);
INSERT INTO son (id,  apgar1,  apgar10,  apgar5,  asphyxiadelivery,  attachedtime,  bcg,  bornalive,  consistency,  cry,  extremepremature,  gas,  mechanicalventilation, name, of,  og,  ot,  pediatricexamination,  secretion,  secretioncolour, size,  skullperimeter,  tempaxilar,  temprectal,  ticket,  vitk,  weight,  weightplacenta,  delivery_id,  gender_id,  mother_id,  year_id,  profile_id)
VALUES (49,  '4',  '5',  '5', TRUE,  '12', TRUE, TRUE,  'No', TRUE, FALSE, TRUE, TRUE,  'Joffrey Lannister', TRUE, TRUE, TRUE, 37,  'No',  'No',  '34',  '23',  '33',  '34', 58, TRUE,  '2223',  '10', 48, 2, 49, 2012, 99);
INSERT INTO son (id,  apgar1,  apgar10,  apgar5,  asphyxiadelivery,  attachedtime,  bcg,  bornalive,  consistency,  cry,  extremepremature,  gas,  mechanicalventilation, name, of,  og,  ot,  pediatricexamination,  secretion,  secretioncolour, size,  skullperimeter,  tempaxilar,  temprectal,  ticket,  vitk,  weight,  weightplacenta,  delivery_id,  gender_id,  mother_id,  year_id,  profile_id)
VALUES (50,  '4',  '5',  '5', TRUE,  '12', TRUE, TRUE,  'No', TRUE, TRUE, TRUE, TRUE,  'Joffrey Lannister', TRUE, TRUE, TRUE, 30,  'No',  'No',  '34',  '23',  '33',  '34', 59, TRUE,  '2113',  '10', 49, 1, 50, 2013, 100);
INSERT INTO son (id,  apgar1,  apgar10,  apgar5,  asphyxiadelivery,  attachedtime,  bcg,  bornalive,  consistency,  cry,  extremepremature,  gas,  mechanicalventilation, name, of,  og,  ot,  pediatricexamination,  secretion,  secretioncolour, size,  skullperimeter,  tempaxilar,  temprectal,  ticket,  vitk,  weight,  weightplacenta,  delivery_id,  gender_id,  mother_id,  year_id,  profile_id)
VALUES (51,  '4',  '5',  '5', TRUE,  '12', TRUE, TRUE,  'No', TRUE, FALSE, TRUE, TRUE,  'Joffrey Lannister', TRUE, TRUE, TRUE, 31,  'No',  'No',  '34',  '23',  '33',  '34', 60, TRUE,  '2113',  '10', 50, 2, 51, 2014, 101);
INSERT INTO son (id,  apgar1,  apgar10,  apgar5,  asphyxiadelivery,  attachedtime,  bcg,  bornalive,  consistency,  cry,  extremepremature,  gas,  mechanicalventilation, name, of,  og,  ot,  pediatricexamination,  secretion,  secretioncolour, size,  skullperimeter,  tempaxilar,  temprectal,  ticket,  vitk,  weight,  weightplacenta,  delivery_id,  gender_id,  mother_id,  year_id,  profile_id)
VALUES (52,  '4',  '5',  '5', TRUE,  '12', TRUE, TRUE,  'No', TRUE, FALSE, TRUE, TRUE,  'Joffrey Lannister', TRUE, TRUE, TRUE, 32,  'No',  'No',  '34',  '23',  '33',  '34', 61, TRUE,  '2113',  '10', 51, 1, 1, 2010, 102);
INSERT INTO son (id,  apgar1,  apgar10,  apgar5,  asphyxiadelivery,  attachedtime,  bcg,  bornalive,  consistency,  cry,  extremepremature,  gas,  mechanicalventilation, name, of,  og,  ot,  pediatricexamination,  secretion,  secretioncolour, size,  skullperimeter,  tempaxilar,  temprectal,  ticket,  vitk,  weight,  weightplacenta,  delivery_id,  gender_id,  mother_id,  year_id,  profile_id)
VALUES (53,  '4',  '5',  '5', TRUE,  '12', TRUE, TRUE,  'No', TRUE, FALSE, TRUE, TRUE,  'Joffrey Lannister', TRUE, TRUE, TRUE, 33,  'No',  'No',  '34',  '23',  '33',  '34', 62, TRUE,  '2113',  '10', 1, 2, 2, 2011, 103);
INSERT INTO son (id,  apgar1,  apgar10,  apgar5,  asphyxiadelivery,  attachedtime,  bcg,  bornalive,  consistency,  cry,  extremepremature,  gas,  mechanicalventilation, name, of,  og,  ot,  pediatricexamination,  secretion,  secretioncolour, size,  skullperimeter,  tempaxilar,  temprectal,  ticket,  vitk,  weight,  weightplacenta,  delivery_id,  gender_id,  mother_id,  year_id,  profile_id)
VALUES (54,  '4',  '5',  '5', TRUE,  '12', TRUE, TRUE,  'No', TRUE, FALSE, TRUE, TRUE,  'Joffrey Lannister', TRUE, TRUE, TRUE, 34,  'No',  'No',  '34',  '23',  '33',  '34', 63, TRUE,  '2113',  '10', 2, 1, 3, 2012, 104);
INSERT INTO son (id,  apgar1,  apgar10,  apgar5,  asphyxiadelivery,  attachedtime,  bcg,  bornalive,  consistency,  cry,  extremepremature,  gas,  mechanicalventilation, name, of,  og,  ot,  pediatricexamination,  secretion,  secretioncolour, size,  skullperimeter,  tempaxilar,  temprectal,  ticket,  vitk,  weight,  weightplacenta,  delivery_id,  gender_id,  mother_id,  year_id,  profile_id)
VALUES (55,  '4',  '5',  '5', TRUE,  '12', TRUE, TRUE,  'No', TRUE, FALSE, TRUE, TRUE,  'Joffrey Lannister', TRUE, TRUE, TRUE, 35,  'No',  'No',  '34',  '23',  '33',  '34', 64, TRUE,  '2113',  '10', 3, 2, 4, 2013, 105);
INSERT INTO son (id,  apgar1,  apgar10,  apgar5,  asphyxiadelivery,  attachedtime,  bcg,  bornalive,  consistency,  cry,  extremepremature,  gas,  mechanicalventilation, name, of,  og,  ot,  pediatricexamination,  secretion,  secretioncolour, size,  skullperimeter,  tempaxilar,  temprectal,  ticket,  vitk,  weight,  weightplacenta,  delivery_id,  gender_id,  mother_id,  year_id,  profile_id)
VALUES (56,  '4',  '5',  '5', TRUE,  '12', TRUE, TRUE,  'No', TRUE, FALSE, TRUE, TRUE,  'Joffrey Lannister', TRUE, TRUE, TRUE, 36,  'No',  'No',  '34',  '23',  '33',  '34', 65, TRUE,  '2113',  '10', 4, 1, 5, 2014, 106);
INSERT INTO son (id,  apgar1,  apgar10,  apgar5,  asphyxiadelivery,  attachedtime,  bcg,  bornalive,  consistency,  cry,  extremepremature,  gas,  mechanicalventilation, name, of,  og,  ot,  pediatricexamination,  secretion,  secretioncolour, size,  skullperimeter,  tempaxilar,  temprectal,  ticket,  vitk,  weight,  weightplacenta,  delivery_id,  gender_id,  mother_id,  year_id,  profile_id)
VALUES (57,  '4',  '5',  '5', TRUE,  '12', TRUE, TRUE,  'No', TRUE, FALSE, TRUE, TRUE,  'Joffrey Lannister', TRUE, TRUE, TRUE, 37,  'No',  'No',  '34',  '23',  '33',  '34', 66, TRUE,  '2113',  '10', 5, 2, 6, 2010, 107);
INSERT INTO son (id,  apgar1,  apgar10,  apgar5,  asphyxiadelivery,  attachedtime,  bcg,  bornalive,  consistency,  cry,  extremepremature,  gas,  mechanicalventilation, name, of,  og,  ot,  pediatricexamination,  secretion,  secretioncolour, size,  skullperimeter,  tempaxilar,  temprectal,  ticket,  vitk,  weight,  weightplacenta,  delivery_id,  gender_id,  mother_id,  year_id,  profile_id)
VALUES (58,  '4',  '5',  '5', TRUE,  '12', TRUE, TRUE,  'No', TRUE, TRUE, TRUE, TRUE,  'Joffrey Lannister', TRUE, TRUE, TRUE, 30,  'No',  'No',  '34',  '23',  '33',  '34', 67, TRUE,  '2113',  '10', 6, 1, 7, 2011, 108);
INSERT INTO son (id,  apgar1,  apgar10,  apgar5,  asphyxiadelivery,  attachedtime,  bcg,  bornalive,  consistency,  cry,  extremepremature,  gas,  mechanicalventilation, name, of,  og,  ot,  pediatricexamination,  secretion,  secretioncolour, size,  skullperimeter,  tempaxilar,  temprectal,  ticket,  vitk,  weight,  weightplacenta,  delivery_id,  gender_id,  mother_id,  year_id,  profile_id)
VALUES (59,  '4',  '5',  '5', TRUE,  '12', TRUE, TRUE,  'No', TRUE, FALSE, TRUE, TRUE,  'Joffrey Lannister', TRUE, TRUE, TRUE, 31,  'No',  'No',  '34',  '23',  '33',  '34', 68, TRUE,  '2442',  '10', 7, 2, 8, 2012, 109);
INSERT INTO son (id,  apgar1,  apgar10,  apgar5,  asphyxiadelivery,  attachedtime,  bcg,  bornalive,  consistency,  cry,  extremepremature,  gas,  mechanicalventilation, name, of,  og,  ot,  pediatricexamination,  secretion,  secretioncolour, size,  skullperimeter,  tempaxilar,  temprectal,  ticket,  vitk,  weight,  weightplacenta,  delivery_id,  gender_id,  mother_id,  year_id,  profile_id)
VALUES (60,  '4',  '5',  '5', TRUE,  '12', TRUE, TRUE,  'No', TRUE, FALSE, TRUE, TRUE,  'Joffrey Lannister', TRUE, TRUE, TRUE, 32,  'No',  'No',  '34',  '23',  '33',  '34', 69, TRUE,  '2442',  '10', 8, 1, 9, 2013, 110);
INSERT INTO son (id,  apgar1,  apgar10,  apgar5,  asphyxiadelivery,  attachedtime,  bcg,  bornalive,  consistency,  cry,  extremepremature,  gas,  mechanicalventilation, name, of,  og,  ot,  pediatricexamination,  secretion,  secretioncolour, size,  skullperimeter,  tempaxilar,  temprectal,  ticket,  vitk,  weight,  weightplacenta,  delivery_id,  gender_id,  mother_id,  year_id,  profile_id)
VALUES (61,  '4',  '5',  '5', TRUE,  '12', TRUE, TRUE,  'No', TRUE, FALSE, TRUE, TRUE,  'Joffrey Lannister', TRUE, TRUE, TRUE, 33,  'No',  'No',  '34',  '23',  '33',  '34', 70, TRUE,  '2442',  '10', 9, 2, 10, 2014, 111);
INSERT INTO son (id,  apgar1,  apgar10,  apgar5,  asphyxiadelivery,  attachedtime,  bcg,  bornalive,  consistency,  cry,  extremepremature,  gas,  mechanicalventilation, name, of,  og,  ot,  pediatricexamination,  secretion,  secretioncolour, size,  skullperimeter,  tempaxilar,  temprectal,  ticket,  vitk,  weight,  weightplacenta,  delivery_id,  gender_id,  mother_id,  year_id,  profile_id)
VALUES (62,  '4',  '5',  '5', TRUE,  '12', TRUE, TRUE,  'No', TRUE, FALSE, TRUE, TRUE,  'Joffrey Lannister', TRUE, TRUE, TRUE, 34,  'No',  'No',  '34',  '23',  '33',  '34', 71, TRUE,  '2442',  '10', 10, 1, 11, 2010, 112);
INSERT INTO son (id,  apgar1,  apgar10,  apgar5,  asphyxiadelivery,  attachedtime,  bcg,  bornalive,  consistency,  cry,  extremepremature,  gas,  mechanicalventilation, name, of,  og,  ot,  pediatricexamination,  secretion,  secretioncolour, size,  skullperimeter,  tempaxilar,  temprectal,  ticket,  vitk,  weight,  weightplacenta,  delivery_id,  gender_id,  mother_id,  year_id,  profile_id)
VALUES (63,  '4',  '5',  '5', TRUE,  '12', TRUE, TRUE,  'No', TRUE, FALSE, TRUE, TRUE,  'Joffrey Lannister', TRUE, TRUE, TRUE, 35,  'No',  'No',  '34',  '23',  '33',  '34', 72, TRUE,  '2442',  '10', 11, 2, 12, 2011, 113);
INSERT INTO son (id,  apgar1,  apgar10,  apgar5,  asphyxiadelivery,  attachedtime,  bcg,  bornalive,  consistency,  cry,  extremepremature,  gas,  mechanicalventilation, name, of,  og,  ot,  pediatricexamination,  secretion,  secretioncolour, size,  skullperimeter,  tempaxilar,  temprectal,  ticket,  vitk,  weight,  weightplacenta,  delivery_id,  gender_id,  mother_id,  year_id,  profile_id)
VALUES (64,  '4',  '5',  '5', TRUE,  '12', TRUE, TRUE,  'No', TRUE, FALSE, TRUE, TRUE,  'Joffrey Lannister', TRUE, TRUE, TRUE, 36,  'No',  'No',  '34',  '23',  '33',  '34', 73, TRUE,  '2442',  '10', 12, 1, 13, 2012, 114);
INSERT INTO son (id,  apgar1,  apgar10,  apgar5,  asphyxiadelivery,  attachedtime,  bcg,  bornalive,  consistency,  cry,  extremepremature,  gas,  mechanicalventilation, name, of,  og,  ot,  pediatricexamination,  secretion,  secretioncolour, size,  skullperimeter,  tempaxilar,  temprectal,  ticket,  vitk,  weight,  weightplacenta,  delivery_id,  gender_id,  mother_id,  year_id,  profile_id)
VALUES (65,  '4',  '5',  '5', TRUE,  '12', TRUE, TRUE,  'No', TRUE, FALSE, TRUE, TRUE,  'Joffrey Lannister', TRUE, TRUE, TRUE, 37,  'No',  'No',  '34',  '23',  '33',  '34', 74, TRUE,  '2442',  '10', 13, 2, 14, 2013, 115);
INSERT INTO son (id,  apgar1,  apgar10,  apgar5,  asphyxiadelivery,  attachedtime,  bcg,  bornalive,  consistency,  cry,  extremepremature,  gas,  mechanicalventilation, name, of,  og,  ot,  pediatricexamination,  secretion,  secretioncolour, size,  skullperimeter,  tempaxilar,  temprectal,  ticket,  vitk,  weight,  weightplacenta,  delivery_id,  gender_id,  mother_id,  year_id,  profile_id)
VALUES (66,  '4',  '5',  '5', TRUE,  '12', TRUE, TRUE,  'No', TRUE, TRUE, TRUE, TRUE,  'Joffrey Lannister', TRUE, TRUE, TRUE, 30,  'No',  'No',  '34',  '23',  '33',  '34', 75, TRUE,  '2442',  '10', 14, 1, 15, 2014, 116);
INSERT INTO son (id,  apgar1,  apgar10,  apgar5,  asphyxiadelivery,  attachedtime,  bcg,  bornalive,  consistency,  cry,  extremepremature,  gas,  mechanicalventilation, name, of,  og,  ot,  pediatricexamination,  secretion,  secretioncolour, size,  skullperimeter,  tempaxilar,  temprectal,  ticket,  vitk,  weight,  weightplacenta,  delivery_id,  gender_id,  mother_id,  year_id,  profile_id)
VALUES (67,  '4',  '5',  '5', TRUE,  '12', TRUE, TRUE,  'No', TRUE, FALSE, TRUE, TRUE,  'Joffrey Lannister', TRUE, TRUE, TRUE, 31,  'No',  'No',  '34',  '23',  '33',  '34', 76, TRUE,  '2442',  '10', 15, 2, 16, 2010, 117);
INSERT INTO son (id,  apgar1,  apgar10,  apgar5,  asphyxiadelivery,  attachedtime,  bcg,  bornalive,  consistency,  cry,  extremepremature,  gas,  mechanicalventilation, name, of,  og,  ot,  pediatricexamination,  secretion,  secretioncolour, size,  skullperimeter,  tempaxilar,  temprectal,  ticket,  vitk,  weight,  weightplacenta,  delivery_id,  gender_id,  mother_id,  year_id,  profile_id)
VALUES (68,  '4',  '5',  '5', TRUE,  '12', TRUE, TRUE,  'No', TRUE, FALSE, TRUE, TRUE,  'Joffrey Lannister', TRUE, TRUE, TRUE, 32,  'No',  'No',  '34',  '23',  '33',  '34', 77, TRUE,  '2442',  '10', 16, 1, 17, 2011, 118);
INSERT INTO son (id,  apgar1,  apgar10,  apgar5,  asphyxiadelivery,  attachedtime,  bcg,  bornalive,  consistency,  cry,  extremepremature,  gas,  mechanicalventilation, name, of,  og,  ot,  pediatricexamination,  secretion,  secretioncolour, size,  skullperimeter,  tempaxilar,  temprectal,  ticket,  vitk,  weight,  weightplacenta,  delivery_id,  gender_id,  mother_id,  year_id,  profile_id)
VALUES (69,  '4',  '5',  '5', TRUE,  '12', TRUE, TRUE,  'No', TRUE, FALSE, TRUE, TRUE,  'Joffrey Lannister', TRUE, TRUE, TRUE, 33,  'No',  'No',  '34',  '23',  '33',  '34', 78, TRUE,  '2442',  '10', 17, 2, 18, 2012, 119);
INSERT INTO son (id,  apgar1,  apgar10,  apgar5,  asphyxiadelivery,  attachedtime,  bcg,  bornalive,  consistency,  cry,  extremepremature,  gas,  mechanicalventilation, name, of,  og,  ot,  pediatricexamination,  secretion,  secretioncolour, size,  skullperimeter,  tempaxilar,  temprectal,  ticket,  vitk,  weight,  weightplacenta,  delivery_id,  gender_id,  mother_id,  year_id,  profile_id)
VALUES (70,  '4',  '5',  '5', TRUE,  '12', TRUE, TRUE,  'No', TRUE, FALSE, TRUE, TRUE,  'Joffrey Lannister', TRUE, TRUE, TRUE, 34,  'No',  'No',  '34',  '23',  '33',  '34', 79, TRUE,  '2442',  '10', 18, 1, 19, 2013, 120);
INSERT INTO son (id,  apgar1,  apgar10,  apgar5,  asphyxiadelivery,  attachedtime,  bcg,  bornalive,  consistency,  cry,  extremepremature,  gas,  mechanicalventilation, name, of,  og,  ot,  pediatricexamination,  secretion,  secretioncolour, size,  skullperimeter,  tempaxilar,  temprectal,  ticket,  vitk,  weight,  weightplacenta,  delivery_id,  gender_id,  mother_id,  year_id,  profile_id)
VALUES (71,  '4',  '5',  '5', TRUE,  '12', TRUE, TRUE,  'No', TRUE, FALSE, TRUE, TRUE,  'Joffrey Lannister', TRUE, TRUE, TRUE, 35,  'No',  'No',  '34',  '23',  '33',  '34', 80, TRUE,  '2442',  '10', 19, 2, 20, 2014, 121);
INSERT INTO son (id,  apgar1,  apgar10,  apgar5,  asphyxiadelivery,  attachedtime,  bcg,  bornalive,  consistency,  cry,  extremepremature,  gas,  mechanicalventilation, name, of,  og,  ot,  pediatricexamination,  secretion,  secretioncolour, size,  skullperimeter,  tempaxilar,  temprectal,  ticket,  vitk,  weight,  weightplacenta,  delivery_id,  gender_id,  mother_id,  year_id,  profile_id)
VALUES (72,  '4',  '5',  '5', TRUE,  '12', TRUE, TRUE,  'No', TRUE, FALSE, TRUE, TRUE,  'Joffrey Lannister', TRUE, TRUE, TRUE, 36,  'No',  'No',  '34',  '23',  '33',  '34', 81, TRUE,  '2442',  '10', 20, 1, 21, 2010, 122);
INSERT INTO son (id,  apgar1,  apgar10,  apgar5,  asphyxiadelivery,  attachedtime,  bcg,  bornalive,  consistency,  cry,  extremepremature,  gas,  mechanicalventilation, name, of,  og,  ot,  pediatricexamination,  secretion,  secretioncolour, size,  skullperimeter,  tempaxilar,  temprectal,  ticket,  vitk,  weight,  weightplacenta,  delivery_id,  gender_id,  mother_id,  year_id,  profile_id)
VALUES (73,  '4',  '5',  '5', TRUE,  '12', TRUE, TRUE,  'No', TRUE, FALSE, TRUE, TRUE,  'Joffrey Lannister', TRUE, TRUE, TRUE, 37,  'No',  'No',  '34',  '23',  '33',  '34', 82, TRUE,  '2442',  '10', 21, 2, 22, 2011, 123);
INSERT INTO son (id,  apgar1,  apgar10,  apgar5,  asphyxiadelivery,  attachedtime,  bcg,  bornalive,  consistency,  cry,  extremepremature,  gas,  mechanicalventilation, name, of,  og,  ot,  pediatricexamination,  secretion,  secretioncolour, size,  skullperimeter,  tempaxilar,  temprectal,  ticket,  vitk,  weight,  weightplacenta,  delivery_id,  gender_id,  mother_id,  year_id,  profile_id)
VALUES (74,  '4',  '5',  '5', TRUE,  '12', TRUE, TRUE,  'No', TRUE, TRUE, TRUE, TRUE,  'Joffrey Lannister', TRUE, TRUE, TRUE, 30,  'No',  'No',  '34',  '23',  '33',  '34', 83, TRUE,  '1422',  '10', 22, 1, 23, 2012, 124);
INSERT INTO son (id,  apgar1,  apgar10,  apgar5,  asphyxiadelivery,  attachedtime,  bcg,  bornalive,  consistency,  cry,  extremepremature,  gas,  mechanicalventilation, name, of,  og,  ot,  pediatricexamination,  secretion,  secretioncolour, size,  skullperimeter,  tempaxilar,  temprectal,  ticket,  vitk,  weight,  weightplacenta,  delivery_id,  gender_id,  mother_id,  year_id,  profile_id)
VALUES (75,  '4',  '5',  '5', TRUE,  '12', TRUE, TRUE,  'No', TRUE, FALSE, TRUE, TRUE,  'Joffrey Lannister', TRUE, TRUE, TRUE, 31,  'No',  'No',  '34',  '23',  '33',  '34', 84, TRUE,  '2442',  '10', 23, 2, 24, 2013, 125);
INSERT INTO son (id,  apgar1,  apgar10,  apgar5,  asphyxiadelivery,  attachedtime,  bcg,  bornalive,  consistency,  cry,  extremepremature,  gas,  mechanicalventilation, name, of,  og,  ot,  pediatricexamination,  secretion,  secretioncolour, size,  skullperimeter,  tempaxilar,  temprectal,  ticket,  vitk,  weight,  weightplacenta,  delivery_id,  gender_id,  mother_id,  year_id,  profile_id)
VALUES (76,  '4',  '5',  '5', TRUE,  '12', TRUE, TRUE,  'No', TRUE, FALSE, TRUE, TRUE,  'Joffrey Lannister', TRUE, TRUE, TRUE, 32,  'No',  'No',  '34',  '23',  '33',  '34', 85, TRUE,  '2442',  '10', 24, 1, 25, 2014, 126);
INSERT INTO son (id,  apgar1,  apgar10,  apgar5,  asphyxiadelivery,  attachedtime,  bcg,  bornalive,  consistency,  cry,  extremepremature,  gas,  mechanicalventilation, name, of,  og,  ot,  pediatricexamination,  secretion,  secretioncolour, size,  skullperimeter,  tempaxilar,  temprectal,  ticket,  vitk,  weight,  weightplacenta,  delivery_id,  gender_id,  mother_id,  year_id,  profile_id)
VALUES (77,  '4',  '5',  '5', TRUE,  '12', TRUE, TRUE,  'No', TRUE, FALSE, TRUE, TRUE,  'Joffrey Lannister', TRUE, TRUE, TRUE, 33,  'No',  'No',  '34',  '23',  '33',  '34', 86, TRUE,  '2442',  '10', 25, 2, 26, 2010, 127);
INSERT INTO son (id,  apgar1,  apgar10,  apgar5,  asphyxiadelivery,  attachedtime,  bcg,  bornalive,  consistency,  cry,  extremepremature,  gas,  mechanicalventilation, name, of,  og,  ot,  pediatricexamination,  secretion,  secretioncolour, size,  skullperimeter,  tempaxilar,  temprectal,  ticket,  vitk,  weight,  weightplacenta,  delivery_id,  gender_id,  mother_id,  year_id,  profile_id)
VALUES (78,  '4',  '5',  '5', TRUE,  '12', TRUE, TRUE,  'No', TRUE, FALSE, TRUE, TRUE,  'Joffrey Lannister', TRUE, TRUE, TRUE, 34,  'No',  'No',  '34',  '23',  '33',  '34', 87, TRUE,  '2442',  '10', 26, 1, 27, 2011, 128);
INSERT INTO son (id,  apgar1,  apgar10,  apgar5,  asphyxiadelivery,  attachedtime,  bcg,  bornalive,  consistency,  cry,  extremepremature,  gas,  mechanicalventilation, name, of,  og,  ot,  pediatricexamination,  secretion,  secretioncolour, size,  skullperimeter,  tempaxilar,  temprectal,  ticket,  vitk,  weight,  weightplacenta,  delivery_id,  gender_id,  mother_id,  year_id,  profile_id)
VALUES (79,  '4',  '5',  '5', TRUE,  '12', TRUE, TRUE,  'No', TRUE, FALSE, TRUE, TRUE,  'Joffrey Lannister', TRUE, TRUE, TRUE, 35,  'No',  'No',  '34',  '23',  '33',  '34', 88, TRUE,  '2442',  '10', 27, 2, 28, 2012, 129);
INSERT INTO son (id,  apgar1,  apgar10,  apgar5,  asphyxiadelivery,  attachedtime,  bcg,  bornalive,  consistency,  cry,  extremepremature,  gas,  mechanicalventilation, name, of,  og,  ot,  pediatricexamination,  secretion,  secretioncolour, size,  skullperimeter,  tempaxilar,  temprectal,  ticket,  vitk,  weight,  weightplacenta,  delivery_id,  gender_id,  mother_id,  year_id,  profile_id)
VALUES (80,  '4',  '5',  '5', TRUE,  '12', TRUE, TRUE,  'No', TRUE, FALSE, TRUE, TRUE,  'Joffrey Lannister', TRUE, TRUE, TRUE, 36,  'No',  'No',  '34',  '23',  '33',  '34', 89, TRUE,  '2442',  '10', 28, 1, 29, 2013, 130);
INSERT INTO son (id,  apgar1,  apgar10,  apgar5,  asphyxiadelivery,  attachedtime,  bcg,  bornalive,  consistency,  cry,  extremepremature,  gas,  mechanicalventilation, name, of,  og,  ot,  pediatricexamination,  secretion,  secretioncolour, size,  skullperimeter,  tempaxilar,  temprectal,  ticket,  vitk,  weight,  weightplacenta,  delivery_id,  gender_id,  mother_id,  year_id,  profile_id)
VALUES (81,  '4',  '5',  '5', TRUE,  '12', TRUE, TRUE,  'No', TRUE, FALSE, TRUE, TRUE,  'Joffrey Lannister', TRUE, TRUE, TRUE, 37,  'No',  'No',  '34',  '23',  '33',  '34', 90, FALSE,  '1902',  '10', 29, 2, 30, 2014, 131);
INSERT INTO son (id,  apgar1,  apgar10,  apgar5,  asphyxiadelivery,  attachedtime,  bcg,  bornalive,  consistency,  cry,  extremepremature,  gas,  mechanicalventilation, name, of,  og,  ot,  pediatricexamination,  secretion,  secretioncolour, size,  skullperimeter,  tempaxilar,  temprectal,  ticket,  vitk,  weight,  weightplacenta,  delivery_id,  gender_id,  mother_id,  year_id,  profile_id)
VALUES (82,  '4',  '5',  '5', TRUE,  '12', TRUE, TRUE,  'No', TRUE, TRUE, TRUE, TRUE,  'Joffrey Lannister', TRUE, TRUE, TRUE, 30,  'No',  'No',  '34',  '23',  '33',  '34', 91, FALSE,  '1482',  '10', 30, 1, 31, 2010, 132);
INSERT INTO son (id,  apgar1,  apgar10,  apgar5,  asphyxiadelivery,  attachedtime,  bcg,  bornalive,  consistency,  cry,  extremepremature,  gas,  mechanicalventilation, name, of,  og,  ot,  pediatricexamination,  secretion,  secretioncolour, size,  skullperimeter,  tempaxilar,  temprectal,  ticket,  vitk,  weight,  weightplacenta,  delivery_id,  gender_id,  mother_id,  year_id,  profile_id)
VALUES (83,  '4',  '5',  '5', TRUE,  '12', TRUE, TRUE,  'No', TRUE, FALSE, TRUE, TRUE,  'Joffrey Lannister', TRUE, TRUE, TRUE, 31,  'No',  'No',  '34',  '23',  '33',  '34', 92, TRUE,  '1902',  '10', 31, 2, 32, 2011, 133);
INSERT INTO son (id,  apgar1,  apgar10,  apgar5,  asphyxiadelivery,  attachedtime,  bcg,  bornalive,  consistency,  cry,  extremepremature,  gas,  mechanicalventilation, name, of,  og,  ot,  pediatricexamination,  secretion,  secretioncolour, size,  skullperimeter,  tempaxilar,  temprectal,  ticket,  vitk,  weight,  weightplacenta,  delivery_id,  gender_id,  mother_id,  year_id,  profile_id)
VALUES (84,  '4',  '5',  '5', TRUE,  '12', TRUE, TRUE,  'No', TRUE, FALSE, TRUE, TRUE,  'Joffrey Lannister', TRUE, TRUE, TRUE, 32,  'No',  'No',  '34',  '23',  '33',  '34', 93, TRUE,  '1902',  '10', 32, 1, 33, 2012, 134);
INSERT INTO son (id,  apgar1,  apgar10,  apgar5,  asphyxiadelivery,  attachedtime,  bcg,  bornalive,  consistency,  cry,  extremepremature,  gas,  mechanicalventilation, name, of,  og,  ot,  pediatricexamination,  secretion,  secretioncolour, size,  skullperimeter,  tempaxilar,  temprectal,  ticket,  vitk,  weight,  weightplacenta,  delivery_id,  gender_id,  mother_id,  year_id,  profile_id)
VALUES (85,  '4',  '5',  '5', TRUE,  '12', TRUE, TRUE,  'No', TRUE, FALSE, TRUE, TRUE,  'Joffrey Lannister', TRUE, TRUE, TRUE, 33,  'No',  'No',  '34',  '23',  '33',  '34', 94, TRUE,  '1902',  '10', 33, 2, 34, 2013, 135);
INSERT INTO son (id,  apgar1,  apgar10,  apgar5,  asphyxiadelivery,  attachedtime,  bcg,  bornalive,  consistency,  cry,  extremepremature,  gas,  mechanicalventilation, name, of,  og,  ot,  pediatricexamination,  secretion,  secretioncolour, size,  skullperimeter,  tempaxilar,  temprectal,  ticket,  vitk,  weight,  weightplacenta,  delivery_id,  gender_id,  mother_id,  year_id,  profile_id)
VALUES (86,  '4',  '5',  '5', TRUE,  '12', TRUE, TRUE,  'No', TRUE, FALSE, TRUE, TRUE,  'Joffrey Lannister', TRUE, TRUE, TRUE, 34,  'No',  'No',  '34',  '23',  '33',  '34', 95, TRUE,  '1902',  '10', 34, 1, 35, 2014, 136);