VALUES (13,  '',  '',  '1960-06-10',  '', TRUE,  NULL,  'asdasd@asda.cl',  'apellido1', TRUE,  '',  'Nombre1',  '',  '11111111', TRUE,  'Apellido1',  NULL, 14, 3, 1,  '2', 13, 12);
INSERT INTO mother (id,  address,  addressdetail,  birthdate,  city,  coombs,  deafrelatives,  email,  firstlastname,  hasdeafrelatives,  mobile, name,  phone,  run,  ruraladdress,  secondlastname,  bloodgroup_id,  commune_id,  forecasthealth_id,  gender_id,  healthservice_id,  profile_id,  region_id )
VALUES (14,  '',  '',  '1960-06-10',  '', TRUE,  NULL,  'asdasd@asda.cl',  'apellido1', TRUE,  '',  'Nombre1',  '',  '11111111', TRUE,  'Apellido1',  NULL, 15, 2, 2,  '2', 14, 1);
INSERT INTO mother (id,  address,  addressdetail,  birthdate,  city,  coombs,  deafrelatives,  email,  firstlastname,  hasdeafrelatives,  mobile, name,  phone,  run,  ruraladdress,  secondlastname,  bloodgroup_id,  commune_id,  forecasthealth_id,  gender_id,  healthservice_id,  profile_id,  region_id )
VALUES (15,  '',  '',  '1960-06-10',  '', TRUE,  NULL,  'asdasd@asda.cl',  'apellido1', TRUE,  '',  'Nombre1',  '',  '11111111', TRUE,  'Apellido1',  NULL, 16, 3, 1,  '2', 15, 2);
INSERT INTO mother (id,  address,  addressdetail,  birthdate,  city,  coombs,  deafrelatives,  email,  firstlastname,  hasdeafrelatives,  mobile, name,  phone,  run,  ruraladdress,  secondlastname,  bloodgroup_id,  commune_id,  forecasthealth_id,  gender_id,  healthservice_id,  profile_id,  region_id )
VALUES (16,  '',  '',  '1960-06-10',  '', TRUE,  NULL,  'asdasd@asda.cl',  'apellido1', TRUE,  '',  'Nombre1',  '',  '11111111', TRUE,  'Apellido1',  NULL, 17, 2, 2,  '2', 16, 3);
INSERT INTO mother (id,  address,  addressdetail,  birthdate,  city,  coombs,  deafrelatives,  email,  firstlastname,  hasdeafrelatives,  mobile, name,  phone,  run,  ruraladdress,  secondlastname,  bloodgroup_id,  commune_id,  forecasthealth_id,  gender_id,  healthservice_id,  profile_id,  region_id )
VALUES (17,  '',  '',  '1960-06-10',  '', TRUE,  NULL,  'asdasd@asda.cl',  'apellido1', TRUE,  '',  'Nombre1',  '',  '11111111', TRUE,  'Apellido1',  NULL, 18, 2, 1,  '2', 17, 4);
INSERT INTO mother (id,  address,  addressdetail,  birthdate,  city,  coombs,  deafrelatives,  email,  firstlastname,  hasdeafrelatives,  mobile, name,  phone,  run,  ruraladdress,  secondlastname,  bloodgroup_id,  commune_id,  forecasthealth_id,  gender_id,  healthservice_id,  profile_id,  region_id )
VALUES (18,  '',  '',  '1960-06-10',  '', TRUE,  NULL,  'asdasd@asda.cl',  'apellido1', TRUE,  '',  'Nombre1',  '',  '11111111', TRUE,  'Apellido1',  NULL, 19, 2, 2,  '2', 18, 5);
INSERT INTO mother (id,  address,  addressdetail,  birthdate,  city,  coombs,  deafrelatives,  email,  firstlastname,  hasdeafrelatives,  mobile, name,  phone,  run,  ruraladdress,  secondlastname,  bloodgroup_id,  commune_id,  forecasthealth_id,  gender_id,  healthservice_id,  profile_id,  region_id )
VALUES (19,  '',  '',  '1960-06-10',  '', TRUE,  NULL,  'asdasd@asda.cl',  'apellido1', TRUE,  '',  'Nombre1',  '',  '11111111', TRUE,  'Apellido1',  NULL, 20, 3, 1,  '2', 19, 6);
INSERT INTO mother (id,  address,  addressdetail,  birthdate,  city,  coombs,  deafrelatives,  email,  firstlastname,  hasdeafrelatives,  mobile, name,  phone,  run,  ruraladdress,  secondlastname,  bloodgroup_id,  commune_id,  forecasthealth_id,  gender_id,  healthservice_id,  profile_id,  region_id )
VALUES (20,  '',  '',  '1960-06-10',  '', TRUE,  NULL,  'asdasd@asda.cl',  'apellido1', TRUE,  '',  'Nombre1',  '',  '11111111', TRUE,  'Apellido1',  NULL, 21, 2, 2,  '2', 20, 7);
INSERT INTO mother (id,  address,  addressdetail,  birthdate,  city,  coombs,  deafrelatives,  email,  firstlastname,  hasdeafrelatives,  mobile, name,  phone,  run,  ruraladdress,  secondlastname,  bloodgroup_id,  commune_id,  forecasthealth_id,  gender_id,  healthservice_id,  profile_id,  region_id )
VALUES (21,  '',  '',  '1960-06-10',  '', TRUE,  NULL,  'asdasd@asda.cl',  'apellido1', TRUE,  '',  'Nombre1',  '',  '11111111', TRUE,  'Apellido1',  NULL, 22, 2, 1,  '2', 21, 8);
INSERT INTO mother (id,  address,  addressdetail,  birthdate,  city,  coombs,  deafrelatives,  email,  firstlastname,  hasdeafrelatives,  mobile, name,  phone,  run,  ruraladdress,  secondlastname,  bloodgroup_id,  commune_id,  forecasthealth_id,  gender_id,  healthservice_id,  profile_id,  region_id )
VALUES (22,  '',  '',  '1960-06-10',  '', TRUE,  NULL,  'asdasd@asda.cl',  'apellido1', TRUE,  '',  'Nombre1',  '',  '11111111', TRUE,  'Apellido1',  NULL, 23, 2, 2,  '2', 22, 9);
INSERT INTO mother (id,  address,  addressdetail,  birthdate,  city,  coombs,  deafrelatives,  email,  firstlastname,  hasdeafrelatives,  mobile, name,  phone,  run,  ruraladdress,  secondlastname,  bloodgroup_id,  commune_id,  forecasthealth_id,  gender_id,  healthservice_id,  profile_id,  region_id )
VALUES (23,  '',  '',  '1960-06-10',  '', TRUE,  NULL,  'asdasd@asda.cl',  'apellido1', TRUE,  '',  'Nombre1',  '',  '11111111', TRUE,  'Apellido1',  NULL, 24, 1, 1,  '2', 23, 10);
INSERT INTO mother (id,  address,  addressdetail,  birthdate,  city,  coombs,  deafrelatives,  email,  firstlastname,  hasdeafrelatives,  mobile, name,  phone,  run,  ruraladdress,  secondlastname,  bloodgroup_id,  commune_id,  forecasthealth_id,  gender_id,  healthservice_id,  profile_id,  region_id )
VALUES (24,  '',  '',  '1960-06-10',  '', TRUE,  NULL,  'asdasd@asda.cl',  'apellido1', TRUE,  '',  'Nombre1',  '',  '11111111', TRUE,  'Apellido1',  NULL, 25, 1, 2,  '2', 24, 11);
INSERT INTO mother (id,  address,  addressdetail,  birthdate,  city,  coombs,  deafrelatives,  email,  firstlastname,  hasdeafrelatives,  mobile, name,  phone,  run,  ruraladdress,  secondlastname,  bloodgroup_id,  commune_id,  forecasthealth_id,  gender_id,  healthservice_id,  profile_id,  region_id )
VALUES (25,  '',  '',  '1960-06-10',  '', TRUE,  NULL,  'asdasd@asda.cl',  'apellido1', TRUE,  '',  'Nombre1',  '',  '11111111', TRUE,  'Apellido1',  NULL, 26, 1, 1,  '2', 25, 12);
INSERT INTO mother (id,  address,  addressdetail,  birthdate,  city,  coombs,  deafrelatives,  email,  firstlastname,  hasdeafrelatives,  mobile, name,  phone,  run,  ruraladdress,  secondlastname,  bloodgroup_id,  commune_id,  forecasthealth_id,  gender_id,  healthservice_id,  profile_id,  region_id )
VALUES (26,  '',  '',  '1960-06-10',  '', TRUE,  NULL,  'asdasd@asda.cl',  'apellido1', TRUE,  '',  'Nombre1',  '',  '11111111', TRUE,  'Apellido1',  NULL, 27, 1, 2,  '2', 26, 1);
INSERT INTO mother (id,  address,  addressdetail,  birthdate,  city,  coombs,  deafrelatives,  email,  firstlastname,  hasdeafrelatives,  mobile, name,  phone,  run,  ruraladdress,  secondlastname,  bloodgroup_id,  commune_id,  forecasthealth_id,  gender_id,  healthservice_id,  profile_id,  region_id )
VALUES (27,  '',  '',  '1960-06-10',  '', TRUE,  NULL,  'asdasd@asda.cl',  'apellido1', TRUE,  '',  'Nombre1',  '',  '11111111', TRUE,  'Apellido1',  NULL, 28, 1, 1,  '2', 27, 2);
INSERT INTO mother (id,  address,  addressdetail,  birthdate,  city,  coombs,  deafrelatives,  email,  firstlastname,  hasdeafrelatives,  mobile, name,  phone,  run,  ruraladdress,  secondlastname,  bloodgroup_id,  commune_id,  forecasthealth_id,  gender_id,  healthservice_id,  profile_id,  region_id )
VALUES (28,  '',  '',  '1960-06-10',  '', TRUE,  NULL,  'asdasd@asda.cl',  'apellido1', TRUE,  '',  'Nombre1',  '',  '11111111', TRUE,  'Apellido1',  NULL, 29, 3, 2,  '2', 28, 3);
INSERT INTO mother (id,  address,  addressdetail,  birthdate,  city,  coombs,  deafrelatives,  email,  firstlastname,  hasdeafrelatives,  mobile, name,  phone,  run,  ruraladdress,  secondlastname,  bloodgroup_id,  commune_id,  forecasthealth_id,  gender_id,  healthservice_id,  profile_id,  region_id )
VALUES (29,  '',  '',  '1960-06-10',  '', TRUE,  NULL,  'asdasd@asda.cl',  'apellido1', TRUE,  '',  'Nombre1',  '',  '11111111', TRUE,  'Apellido1',  NULL, 30, 1, 1,  '2', 29, 4);
INSERT INTO mother (id,  address,  addressdetail,  birthdate,  city,  coombs,  deafrelatives,  email,  firstlastname,  hasdeafrelatives,  mobile, name,  phone,  run,  ruraladdress,  secondlastname,  bloodgroup_id,  commune_id,  forecasthealth_id,  gender_id,  healthservice_id,  profile_id,  region_id )
VALUES (30,  '',  '',  '1960-06-10',  '', TRUE,  NULL,  'asdasd@asda.cl',  'apellido1', TRUE,  '',  'Nombre1',  '',  '11111111', TRUE,  'Apellido1',  NULL, 31, 2, 2,  '2', 30, 5);
INSERT INTO mother (id,  address,  addressdetail,  birthdate,  city,  coombs,  deafrelatives,  email,  firstlastname,  hasdeafrelatives,  mobile, name,  phone,  run,  ruraladdress,  secondlastname,  bloodgroup_id,  commune_id,  forecasthealth_id,  gender_id,  healthservice_id,  profile_id,  region_id )
VALUES (31,  '',  '',  '1960-06-10',  '', TRUE,  NULL,  'asdasd@asda.cl',  'apellido1', TRUE,  '',  'Nombre1',  '',  '11111111', TRUE,  'Apellido1',  NULL, 32, 2, 1,  '2', 31, 6);
INSERT INTO mother (id,  address,  addressdetail,  birthdate,  city,  coombs,  deafrelatives,  email,  firstlastname,  hasdeafrelatives,  mobile, name,  phone,  run,  ruraladdress,  secondlastname,  bloodgroup_id,  commune_id,  forecasthealth_id,  gender_id,  healthservice_id,  profile_id,  region_id )
VALUES (32,  '',  '',  '1960-06-10',  '', TRUE,  NULL,  'asdasd@asda.cl',  'apellido1', TRUE,  '',  'Nombre1',  '',  '11111111', TRUE,  'Apellido1',  NULL, 33, 2, 2,  '2', 32, 7);
INSERT INTO mother (id,  address,  addressdetail,  birthdate,  city,  coombs,  deafrelatives,  email,  firstlastname,  hasdeafrelatives,  mobile, name,  phone,  run,  ruraladdress,  secondlastname,  bloodgroup_id,  commune_id,  forecasthealth_id,  gender_id,  healthservice_id,  profile_id,  region_id )
VALUES (33,  '',  '',  '1960-06-10',  '', TRUE,  NULL,  'asdasd@asda.cl',  'apellido1', TRUE,  '',  'Nombre1',  '',  '11111111', TRUE,  'Apellido1',  NULL, 34, 2, 1,  '2', 33, 8);
INSERT INTO mother (id,  address,  addressdetail,  birthdate,  city,  coombs,  deafrelatives,  email,  firstlastname,  hasdeafrelatives,  mobile, name,  phone,  run,  ruraladdress,  secondlastname,  bloodgroup_id,  commune_id,  forecasthealth_id,  gender_id,  healthservice_id,  profile_id,  region_id )
VALUES (34,  '',  '',  '1960-06-10',  '', TRUE,  NULL,  'asdasd@asda.cl',  'apellido1', TRUE,  '',  'Nombre1',  '',  '11111111', TRUE,  'Apellido1',  NULL, 35, 2, 2,  '2', 34, 9);
INSERT INTO mother (id,  address,  addressdetail,  birthdate,  city,  coombs,  deafrelatives,  email,  firstlastname,  hasdeafrelatives,  mobile, name,  phone,  run,  ruraladdress,  secondlastname,  bloodgroup_id,  commune_id,  forecasthealth_id,  gender_id,  healthservice_id,  profile_id,  region_id )
VALUES (35,  '',  '',  '1960-06-10',  '', TRUE,  NULL,  'asdasd@asda.cl',  'apellido1', TRUE,  '',  'Nombre1',  '',  '11111111', TRUE,  'Apellido1',  NULL, 36, 2, 1,  '2', 35, 10);
INSERT INTO mother (id,  address,  addressdetail,  birthdate,  city,  coombs,  deafrelatives,  email,  firstlastname,  hasdeafrelatives,  mobile, name,  phone,  run,  ruraladdress,  secondlastname,  bloodgroup_id,  commune_id,  forecasthealth_id,  gender_id,  healthservice_id,  profile_id,  region_id )
VALUES (36,  '',  '',  '1960-06-10',  '', TRUE,  NULL,  'asdasd@asda.cl',  'apellido1', TRUE,  '',  'Nombre1',  '',  '11111111', TRUE,  'Apellido1',  NULL, 37, 2, 1,  '2', 36, 11);
INSERT INTO mother (id,  address,  addressdetail,  birthdate,  city,  coombs,  deafrelatives,  email,  firstlastname,  hasdeafrelatives,  mobile, name,  phone,  run,  ruraladdress,  secondlastname,  bloodgroup_id,  commune_id,  forecasthealth_id,  gender_id,  healthservice_id,  profile_id,  region_id )
VALUES (37,  '',  '',  '1960-06-10',  '', TRUE,  NULL,  'asdasd@asda.cl',  'apellido1', TRUE,  '',  'Nombre1',  '',  '11111111', TRUE,  'Apellido1',  NULL, 38, 1, 2,  '2', 37, 12);
INSERT INTO mother (id,  address,  addressdetail,  birthdate,  city,  coombs,  deafrelatives,  email,  firstlastname,  hasdeafrelatives,  mobile, name,  phone,  run,  ruraladdress,  secondlastname,  bloodgroup_id,  commune_id,  forecasthealth_id,  gender_id,  healthservice_id,  profile_id,  region_id )
VALUES (38,  '',  '',  '1960-06-10',  '', TRUE,  NULL,  'asdasd@asda.cl',  'apellido1', TRUE,  '',  'Nombre1',  '',  '11111111', TRUE,  'Apellido1',  NULL, 39, 1, 2,  '2', 38, 1);
INSERT INTO mother (id,  address,  addressdetail,  birthdate,  city,  coombs,  deafrelatives,  email,  firstlastname,  hasdeafrelatives,  mobile, name,  phone,  run,  ruraladdress,  secondlastname,  bloodgroup_id,  commune_id,  forecasthealth_id,  gender_id,  healthservice_id,  profile_id,  region_id )
VALUES (39,  '',  '',  '1960-06-10',  '', TRUE,  NULL,  'asdasd@asda.cl',  'apellido1', TRUE,  '',  'Nombre1',  '',  '11111111', TRUE,  'Apellido1',  NULL, 40, 3, 2,  '2', 39, 2);
INSERT INTO mother (id,  address,  addressdetail,  birthdate,  city,  coombs,  deafrelatives,  email,  firstlastname,  hasdeafrelatives,  mobile, name,  phone,  run,  ruraladdress,  secondlastname,  bloodgroup_id,  commune_id,  forecasthealth_id,  gender_id,  healthservice_id,  profile_id,  region_id )
VALUES (40,  '',  '',  '1960-06-10',  '', TRUE,  NULL,  'asdasd@asda.cl',  'apellido1', TRUE,  '',  'Nombre1',  '',  '11111111', TRUE,  'Apellido1',  NULL, 41, 2, 1,  '2', 40, 3);
INSERT INTO mother (id,  address,  addressdetail,  birthdate,  city,  coombs,  deafrelatives,  email,  firstlastname,  hasdeafrelatives,  mobile, name,  phone,  run,  ruraladdress,  secondlastname,  bloodgroup_id,  commune_id,  forecasthealth_id,  gender_id,  healthservice_id,  profile_id,  region_id )
VALUES (41,  '',  '',  '1960-06-10',  '', TRUE,  NULL,  'asdasd@asda.cl',  'apellido1', TRUE,  '',  'Nombre1',  '',  '11111111', TRUE,  'Apellido1',  NULL, 42, 2, 1,  '2', 41, 4);
INSERT INTO mother (id,  address,  addressdetail,  birthdate,  city,  coombs,  deafrelatives,  email,  firstlastname,  hasdeafrelatives,  mobile, name,  phone,  run,  ruraladdress,  secondlastname,  bloodgroup_id,  commune_id,  forecasthealth_id,  gender_id,  healthservice_id,  profile_id,  region_id )
VALUES (42,  '',  '',  '1960-06-10',  '', TRUE,  NULL,  'asdasd@asda.cl',  'apellido1', TRUE,  '',  'Nombre1',  '',  '11111111', TRUE,  'Apellido1',  NULL, 43, 2, 2,  '2', 42, 5);
INSERT INTO mother (id,  address,  addressdetail,  birthdate,  city,  coombs,  deafrelatives,  email,  firstlastname,  hasdeafrelatives,  mobile, name,  phone,  run,  ruraladdress,  secondlastname,  bloodgroup_id,  commune_id,  forecasthealth_id,  gender_id,  healthservice_id,  profile_id,  region_id )
VALUES (43,  '',  '',  '1960-06-10',  '', TRUE,  NULL,  'asdasd@asda.cl',  'apellido1', TRUE,  '',  'Nombre1',  '',  '11111111', TRUE,  'Apellido1',  NULL, 44, 1, 2,  '2', 43, 6);
INSERT INTO mother (id,  address,  addressdetail,  birthdate,  city,  coombs,  deafrelatives,  email,  firstlastname,  hasdeafrelatives,  mobile, name,  phone,  run,  ruraladdress,  secondlastname,  bloodgroup_id,  commune_id,  forecasthealth_id,  gender_id,  healthservice_id,  profile_id,  region_id )
VALUES (44,  '',  '',  '1960-06-10',  '', TRUE,  NULL,  'asdasd@asda.cl',  'apellido1', TRUE,  '',  'Nombre1',  '',  '11111111', TRUE,  'Apellido1',  NULL, 45, 2, 2,  '2', 44, 7);
INSERT INTO mother (id,  address,  addressdetail,  birthdate,  city,  coombs,  deafrelatives,  email,  firstlastname,  hasdeafrelatives,  mobile, name,  phone,  run,  ruraladdress,  secondlastname,  bloodgroup_id,  commune_id,  forecasthealth_id,  gender_id,  healthservice_id,  profile_id,  region_id )
VALUES (45,  '',  '',  '1960-06-10',  '', TRUE,  NULL,  'asdasd@asda.cl',  'apellido1', TRUE,  '',  'Nombre1',  '',  '11111111', TRUE,  'Apellido1',  NULL, 46, 3, 2,  '2', 45, 8);
INSERT INTO mother (id,  address,  addressdetail,  birthdate,  city,  coombs,  deafrelatives,  email,  firstlastname,  hasdeafrelatives,  mobile, name,  phone,  run,  ruraladdress,  secondlastname,  bloodgroup_id,  commune_id,  forecasthealth_id,  gender_id,  healthservice_id,  profile_id,  region_id )
VALUES (46,  '',  '',  '1960-06-10',  '', TRUE,  NULL,  'asdasd@asda.cl',  'apellido1', TRUE,  '',  'Nombre1',  '',  '11111111', TRUE,  'Apellido1',  NULL, 47, 2, 3,  '2', 46, 9);
INSERT INTO mother (id,  address,  addressdetail,  birthdate,  city,  coombs,  deafrelatives,  email,  firstlastname,  hasdeafrelatives,  mobile, name,  phone,  run,  ruraladdress,  secondlastname,  bloodgroup_id,  commune_id,  forecasthealth_id,  gender_id,  healthservice_id,  profile_id,  region_id )
VALUES (47,  '',  '',  '1960-06-10',  '', TRUE,  NULL,  'asdasd@asda.cl',  'apellido1', TRUE,  '',  'Nombre1',  '',  '11111111', TRUE,  'Apellido1',  NULL, 48, 2, 2,  '2', 47, 10);
INSERT INTO mother (id,  address,  addressdetail,  birthdate,  city,  coombs,  deafrelatives,  email,  firstlastname,  hasdeafrelatives,  mobile, name,  phone,  run,  ruraladdress,  secondlastname,  bloodgroup_id,  commune_id,  forecasthealth_id,  gender_id,  healthservice_id,  profile_id,  region_id )
VALUES (48,  '',  '',  '1960-06-10',  '', TRUE,  NULL,  'asdasd@asda.cl',  'apellido1', TRUE,  '',  'Nombre1',  '',  '11111111', TRUE,  'Apellido1',  NULL, 49, 3, 3,  '2', 48, 11);
INSERT INTO mother (id,  address,  addressdetail,  birthdate,  city,  coombs,  deafrelatives,  email,  firstlastname,  hasdeafrelatives,  mobile, name,  phone,  run,  ruraladdress,  secondlastname,  bloodgroup_id,  commune_id,  forecasthealth_id,  gender_id,  healthservice_id,  profile_id,  region_id )
VALUES (49,  '',  '',  '1960-06-10',  '', TRUE,  NULL,  'asdasd@asda.cl',  'apellido1', TRUE,  '',  'Nombre1',  '',  '11111111', TRUE,  'Apellido1',  NULL, 50, 2, 3,  '2', 49, 12);
INSERT INTO mother (id,  address,  addressdetail,  birthdate,  city,  coombs,  deafrelatives,  email,  firstlastname,  hasdeafrelatives,  mobile, name,  phone,  run,  ruraladdress,  secondlastname,  bloodgroup_id,  commune_id,  forecasthealth_id,  gender_id,  healthservice_id,  profile_id,  region_id )
VALUES (50,  '',  '',  '1960-06-10',  '', TRUE,  NULL,  'asdasd@asda.cl',  'apellido1', TRUE,  '',  'Nombre1',  '',  '11111111', TRUE,  'Apellido1',  NULL, 51, 3, 1,  '2', 50, 4);
INSERT INTO mother (id,  address,  addressdetail,  birthdate,  city,  coombs,  deafrelatives,  email,  firstlastname,  hasdeafrelatives,  mobile, name,  phone,  run,  ruraladdress,  secondlastname,  bloodgroup_id,  commune_id,  forecasthealth_id,  gender_id,  healthservice_id,  profile_id,  region_id )
VALUES (51,  '',  '',  '1960-06-10',  '', TRUE,  NULL,  'asdasd@asda.cl',  'apellido1', TRUE,  '',  'Nombre1',  '',  '11111111', TRUE,  'Apellido1',  NULL, 52, 2, 2,  '2', 51, 2);