INSERT INTO delivery (id,  anotherpathologydescription,  brokenmembrane,  brokenuterus, date,  diabetes,  dppni,  earlyplacenta,  fetuspain,  hypertension,  laceaccident,  ovularinfection,  polidependencia,  rciu,  rhsensibility,  risk, time,  vdrl,  weeksgestation,  createdby_rut,  deliverytype_id,  mother_id )
VALUES (2,  '', FALSE, FALSE,  '2010-06-22', FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE,  '05:16:34', FALSE, 30,  '164377377', 2, 2);
INSERT INTO delivery (id,  anotherpathologydescription,  brokenmembrane,  brokenuterus, date,  diabetes,  dppni,  earlyplacenta,  fetuspain,  hypertension,  laceaccident,  ovularinfection,  polidependencia,  rciu,  rhsensibility,  risk, time,  vdrl,  weeksgestation,  createdby_rut,  deliverytype_id,  mother_id )
VALUES (3,  '', TRUE, TRUE,  '2011-06-22', TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE,  '05:16:34', TRUE, 31,  '164377377', 3, 3);
INSERT INTO delivery (id,  anotherpathologydescription,  brokenmembrane,  brokenuterus, date,  diabetes,  dppni,  earlyplacenta,  fetuspain,  hypertension,  laceaccident,  ovularinfection,  polidependencia,  rciu,  rhsensibility,  risk, time,  vdrl,  weeksgestation,  createdby_rut,  deliverytype_id,  mother_id )
VALUES (4,  '', TRUE, TRUE,  '2012-06-22', TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE,  '05:16:34', TRUE, 32,  '164377377', 1, 4);
INSERT INTO delivery (id,  anotherpathologydescription,  brokenmembrane,  brokenuterus, date,  diabetes,  dppni,  earlyplacenta,  fetuspain,  hypertension,  laceaccident,  ovularinfection,  polidependencia,  rciu,  rhsensibility,  risk, time,  vdrl,  weeksgestation,  createdby_rut,  deliverytype_id,  mother_id )
VALUES (5,  '', TRUE, TRUE,  '2013-06-22', TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE,  '05:16:34', TRUE, 33,  '164377377', 3, 5);
INSERT INTO delivery (id,  anotherpathologydescription,  brokenmembrane,  brokenuterus, date,  diabetes,  dppni,  earlyplacenta,  fetuspain,  hypertension,  laceaccident,  ovularinfection,  polidependencia,  rciu,  rhsensibility,  risk, time,  vdrl,  weeksgestation,  createdby_rut,  deliverytype_id,  mother_id )
VALUES (6,  '', TRUE, TRUE,  '2014-06-22', TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE,  '05:16:34', TRUE, 34,  '164377377', 4, 6);
INSERT INTO delivery (id,  anotherpathologydescription,  brokenmembrane,  brokenuterus, date,  diabetes,  dppni,  earlyplacenta,  fetuspain,  hypertension,  laceaccident,  ovularinfection,  polidependencia,  rciu,  rhsensibility,  risk, time,  vdrl,  weeksgestation,  createdby_rut,  deliverytype_id,  mother_id )
VALUES (7,  '', TRUE, TRUE,  '2010-06-22', TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE,  '05:16:34', TRUE, 35,  '164377377', 2, 7);
INSERT INTO delivery (id,  anotherpathologydescription,  brokenmembrane,  brokenuterus, date,  diabetes,  dppni,  earlyplacenta,  fetuspain,  hypertension,  laceaccident,  ovularinfection,  polidependencia,  rciu,  rhsensibility,  risk, time,  vdrl,  weeksgestation,  createdby_rut,  deliverytype_id,  mother_id )
VALUES (8,  '', TRUE, TRUE,  '2011-06-22', TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE,  '05:16:34', TRUE, 36,  '164377377', 3, 8);
INSERT INTO delivery (id,  anotherpathologydescription,  brokenmembrane,  brokenuterus, date,  diabetes,  dppni,  earlyplacenta,  fetuspain,  hypertension,  laceaccident,  ovularinfection,  polidependencia,  rciu,  rhsensibility,  risk, time,  vdrl,  weeksgestation,  createdby_rut,  deliverytype_id,  mother_id )
VALUES (9,  '', TRUE, TRUE,  '2012-06-22', TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE,  '05:16:34', TRUE, 37,  '164377377', 2, 9);
INSERT INTO delivery (id,  anotherpathologydescription,  brokenmembrane,  brokenuterus, date,  diabetes,  dppni,  earlyplacenta,  fetuspain,  hypertension,  laceaccident,  ovularinfection,  polidependencia,  rciu,  rhsensibility,  risk, time,  vdrl,  weeksgestation,  createdby_rut,  deliverytype_id,  mother_id )
VALUES (10,  '', TRUE, TRUE,  '2013-06-22', TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE,  '05:16:34', TRUE, 30,  '164377377', 1, 10);
INSERT INTO delivery (id,  anotherpathologydescription,  brokenmembrane,  brokenuterus, date,  diabetes,  dppni,  earlyplacenta,  fetuspain,  hypertension,  laceaccident,  ovularinfection,  polidependencia,  rciu,  rhsensibility,  risk, time,  vdrl,  weeksgestation,  createdby_rut,  deliverytype_id,  mother_id )
VALUES (11,  '', TRUE, TRUE,  '2014-06-22', TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE,  '05:16:34', TRUE, 31,  '164377377', 2, 11);
INSERT INTO delivery (id,  anotherpathologydescription,  brokenmembrane,  brokenuterus, date,  diabetes,  dppni,  earlyplacenta,  fetuspain,  hypertension,  laceaccident,  ovularinfection,  polidependencia,  rciu,  rhsensibility,  risk, time,  vdrl,  weeksgestation,  createdby_rut,  deliverytype_id,  mother_id )
VALUES (12,  '', TRUE, TRUE,  '2010-06-22', TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE,  '05:16:34', TRUE, 32,  '164377377', 3, 12);
INSERT INTO delivery (id,  anotherpathologydescription,  brokenmembrane,  brokenuterus, date,  diabetes,  dppni,  earlyplacenta,  fetuspain,  hypertension,  laceaccident,  ovularinfection,  polidependencia,  rciu,  rhsensibility,  risk, time,  vdrl,  weeksgestation,  createdby_rut,  deliverytype_id,  mother_id )
VALUES (13,  '', TRUE, TRUE,  '2011-06-22', TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE,  '05:16:34', TRUE, 33,  '164377377', 4, 13);
INSERT INTO delivery (id,  anotherpathologydescription,  brokenmembrane,  brokenuterus, date,  diabetes,  dppni,  earlyplacenta,  fetuspain,  hypertension,  laceaccident,  ovularinfection,  polidependencia,  rciu,  rhsensibility,  risk, time,  vdrl,  weeksgestation,  createdby_rut,  deliverytype_id,  mother_id )
VALUES (14,  '', TRUE, TRUE,  '2012-06-22', TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE,  '05:16:34', TRUE, 34,  '164377377', 1, 14);
INSERT INTO delivery (id,  anotherpathologydescription,  brokenmembrane,  brokenuterus, date,  diabetes,  dppni,  earlyplacenta,  fetuspain,  hypertension,  laceaccident,  ovularinfection,  polidependencia,  rciu,  rhsensibility,  risk, time,  vdrl,  weeksgestation,  createdby_rut,  deliverytype_id,  mother_id )
VALUES (15,  '', TRUE, TRUE,  '2013-06-22', TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE,  '05:16:34', TRUE, 35,  '164377377', 2, 15);
INSERT INTO delivery (id,  anotherpathologydescription,  brokenmembrane,  brokenuterus, date,  diabetes,  dppni,  earlyplacenta,  fetuspain,  hypertension,  laceaccident,  ovularinfection,  polidependencia,  rciu,  rhsensibility,  risk, time,  vdrl,  weeksgestation,  createdby_rut,  deliverytype_id,  mother_id )
VALUES (16,  '', TRUE, TRUE,  '2014-06-22', TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE,  '05:16:34', TRUE, 36,  '164377377', 3, 16);
INSERT INTO delivery (id,  anotherpathologydescription,  brokenmembrane,  brokenuterus, date,  diabetes,  dppni,  earlyplacenta,  fetuspain,  hypertension,  laceaccident,  ovularinfection,  polidependencia,  rciu,  rhsensibility,  risk, time,  vdrl,  weeksgestation,  createdby_rut,  deliverytype_id,  mother_id )
VALUES (17,  '', TRUE, TRUE,  '2010-06-22', TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE,  '05:16:34', TRUE, 37,  '164377377', 4, 17);
INSERT INTO delivery (id,  anotherpathologydescription,  brokenmembrane,  brokenuterus, date,  diabetes,  dppni,  earlyplacenta,  fetuspain,  hypertension,  laceaccident,  ovularinfection,  polidependencia,  rciu,  rhsensibility,  risk, time,  vdrl,  weeksgestation,  createdby_rut,  deliverytype_id,  mother_id )
VALUES (18,  '', TRUE, TRUE,  '2011-06-22', TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE,  '05:16:34', TRUE, 30,  '164377377', 2, 18);
INSERT INTO delivery (id,  anotherpathologydescription,  brokenmembrane,  brokenuterus, date,  diabetes,  dppni,  earlyplacenta,  fetuspain,  hypertension,  laceaccident,  ovularinfection,  polidependencia,  rciu,  rhsensibility,  risk, time,  vdrl,  weeksgestation,  createdby_rut,  deliverytype_id,  mother_id )
VALUES (19,  '', TRUE, TRUE,  '2012-06-22', TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE,  '05:16:34', TRUE, 31,  '164377377', 2, 19);
INSERT INTO delivery (id,  anotherpathologydescription,  brokenmembrane,  brokenuterus, date,  diabetes,  dppni,  earlyplacenta,  fetuspain,  hypertension,  laceaccident,  ovularinfection,  polidependencia,  rciu,  rhsensibility,  risk, time,  vdrl,  weeksgestation,  createdby_rut,  deliverytype_id,  mother_id )
VALUES (20,  '', TRUE, TRUE,  '2013-06-22', TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE,  '05:16:34', TRUE, 32,  '164377377', 2, 20);
INSERT INTO delivery (id,  anotherpathologydescription,  brokenmembrane,  brokenuterus, date,  diabetes,  dppni,  earlyplacenta,  fetuspain,  hypertension,  laceaccident,  ovularinfection,  polidependencia,  rciu,  rhsensibility,  risk, time,  vdrl,  weeksgestation,  createdby_rut,  deliverytype_id,  mother_id )
VALUES (21,  '', TRUE, TRUE,  '2014-06-22', TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE,  '05:16:34', TRUE, 33,  '164377377', 1, 21);
INSERT INTO delivery (id,  anotherpathologydescription,  brokenmembrane,  brokenuterus, date,  diabetes,  dppni,  earlyplacenta,  fetuspain,  hypertension,  laceaccident,  ovularinfection,  polidependencia,  rciu,  rhsensibility,  risk, time,  vdrl,  weeksgestation,  createdby_rut,  deliverytype_id,  mother_id )
VALUES (22,  '', TRUE, TRUE,  '2010-06-22', TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE,  '05:16:34', TRUE, 34,  '164377377', 3, 22);
INSERT INTO delivery (id,  anotherpathologydescription,  brokenmembrane,  brokenuterus, date,  diabetes,  dppni,  earlyplacenta,  fetuspain,  hypertension,  laceaccident,  ovularinfection,  polidependencia,  rciu,  rhsensibility,  risk, time,  vdrl,  weeksgestation,  createdby_rut,  deliverytype_id,  mother_id )
VALUES (23,  '', TRUE, TRUE,  '2011-06-22', TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE,  '05:16:34', TRUE, 35,  '164377377', 4, 23);
INSERT INTO delivery (id,  anotherpathologydescription,  brokenmembrane,  brokenuterus, date,  diabetes,  dppni,  earlyplacenta,  fetuspain,  hypertension,  laceaccident,  ovularinfection,  polidependencia,  rciu,  rhsensibility,  risk, time,  vdrl,  weeksgestation,  createdby_rut,  deliverytype_id,  mother_id )
VALUES (24,  '', TRUE, TRUE,  '2012-06-22', TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE,  '05:16:34', TRUE, 36,  '164377377', 3, 24);
INSERT INTO delivery (id,  anotherpathologydescription,  brokenmembrane,  brokenuterus, date,  diabetes,  dppni,  earlyplacenta,  fetuspain,  hypertension,  laceaccident,  ovularinfection,  polidependencia,  rciu,  rhsensibility,  risk, time,  vdrl,  weeksgestation,  createdby_rut,  deliverytype_id,  mother_id )
VALUES (25,  '', TRUE, TRUE,  '2013-06-22', TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE,  '05:16:34', TRUE, 37,  '164377377', 1, 25);
INSERT INTO delivery (id,  anotherpathologydescription,  brokenmembrane,  brokenuterus, date,  diabetes,  dppni,  earlyplacenta,  fetuspain,  hypertension,  laceaccident,  ovularinfection,  polidependencia,  rciu,  rhsensibility,  risk, time,  vdrl,  weeksgestation,  createdby_rut,  deliverytype_id,  mother_id )
VALUES (26,  '', TRUE, TRUE,  '2014-06-22', TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE,  '05:16:34', TRUE, 30,  '164377377', 2, 26);
INSERT INTO delivery (id,  anotherpathologydescription,  brokenmembrane,  brokenuterus, date,  diabetes,  dppni,  earlyplacenta,  fetuspain,  hypertension,  laceaccident,  ovularinfection,  polidependencia,  rciu,  rhsensibility,  risk, time,  vdrl,  weeksgestation,  createdby_rut,  deliverytype_id,  mother_id )
VALUES (27,  '', TRUE, TRUE,  '2010-06-22', TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE,  '05:16:34', TRUE, 31,  '164377377', 3, 27);
INSERT INTO delivery (id,  anotherpathologydescription,  brokenmembrane,  brokenuterus, date,  diabetes,  dppni,  earlyplacenta,  fetuspain,  hypertension,  laceaccident,  ovularinfection,  polidependencia,  rciu,  rhsensibility,  risk, time,  vdrl,  weeksgestation,  createdby_rut,  deliverytype_id,  mother_id )
VALUES (28,  '', TRUE, TRUE,  '2011-06-22', TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE,  '05:16:34', TRUE, 32,  '164377377', 4, 28);
INSERT INTO delivery (id,  anotherpathologydescription,  brokenmembrane,  brokenuterus, date,  diabetes,  dppni,  earlyplacenta,  fetuspain,  hypertension,  laceaccident,  ovularinfection,  polidependencia,  rciu,  rhsensibility,  risk, time,  vdrl,  weeksgestation,  createdby_rut,  deliverytype_id,  mother_id )
VALUES (29,  '', TRUE, TRUE,  '2012-06-22', TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE,  '05:16:34', TRUE, 33,  '164377377', 2, 29);
INSERT INTO delivery (id,  anotherpathologydescription,  brokenmembrane,  brokenuterus, date,  diabetes,  dppni,  earlyplacenta,  fetuspain,  hypertension,  laceaccident,  ovularinfection,  polidependencia,  rciu,  rhsensibility,  risk, time,  vdrl,  weeksgestation,  createdby_rut,  deliverytype_id,  mother_id )
VALUES (30,  '', TRUE, TRUE,  '2013-06-22', TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE,  '05:16:34', TRUE, 34,  '164377377', 4, 30);
INSERT INTO delivery (id,  anotherpathologydescription,  brokenmembrane,  brokenuterus, date,  diabetes,  dppni,  earlyplacenta,  fetuspain,  hypertension,  laceaccident,  ovularinfection,  polidependencia,  rciu,  rhsensibility,  risk, time,  vdrl,  weeksgestation,  createdby_rut,  deliverytype_id,  mother_id )
VALUES (31,  '', TRUE, TRUE,  '2014-06-22', TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE,  '05:16:34', TRUE, 35,  '164377377', 3, 31);
INSERT INTO delivery (id,  anotherpathologydescription,  brokenmembrane,  brokenuterus, date,  diabetes,  dppni,  earlyplacenta,  fetuspain,  hypertension,  laceaccident,  ovularinfection,  polidependencia,  rciu,  rhsensibility,  risk, time,  vdrl,  weeksgestation,  createdby_rut,  deliverytype_id,  mother_id )
VALUES (32,  '', TRUE, TRUE,  '2010-06-22', TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE,  '05:16:34', TRUE, 36,  '164377377', 2, 32);
INSERT INTO delivery (id,  anotherpathologydescription,  brokenmembrane,  brokenuterus, date,  diabetes,  dppni,  earlyplacenta,  fetuspain,  hypertension,  laceaccident,  ovularinfection,  polidependencia,  rciu,  rhsensibility,  risk, time,  vdrl,  weeksgestation,  createdby_rut,  deliverytype_id,  mother_id )
VALUES (33,  '', TRUE, TRUE,  '2011-06-22', TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE,  '05:16:34', TRUE, 37,  '164377377', 1, 33);
INSERT INTO delivery (id,  anotherpathologydescription,  brokenmembrane,  brokenuterus, date,  diabetes,  dppni,  earlyplacenta,  fetuspain,  hypertension,  laceaccident,  ovularinfection,  polidependencia,  rciu,  rhsensibility,  risk, time,  vdrl,  weeksgestation,  createdby_rut,  deliverytype_id,  mother_id )
VALUES (34,  '', TRUE, TRUE,  '2012-06-22', TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE,  '05:16:34', TRUE, 30,  '164377377', 2, 34);
INSERT INTO delivery (id,  anotherpathologydescription,  brokenmembrane,  brokenuterus, date,  diabetes,  dppni,  earlyplacenta,  fetuspain,  hypertension,  laceaccident,  ovularinfection,  polidependencia,  rciu,  rhsensibility,  risk, time,  vdrl,  weeksgestation,  createdby_rut,  deliverytype_id,  mother_id )
VALUES (35,  '', TRUE, TRUE,  '2013-06-22', TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE,  '05:16:34', TRUE, 31,  '164377377', 4, 35);
INSERT INTO delivery (id,  anotherpathologydescription,  brokenmembrane,  brokenuterus, date,  diabetes,  dppni,  earlyplacenta,  fetuspain,  hypertension,  laceaccident,  ovularinfection,  polidependencia,  rciu,  rhsensibility,  risk, time,  vdrl,  weeksgestation,  createdby_rut,  deliverytype_id,  mother_id )
VALUES (36,  '', TRUE, TRUE,  '2014-06-22', TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE,  '05:16:34', TRUE, 32,  '164377377', 3, 36);
INSERT INTO delivery (id,  anotherpathologydescription,  brokenmembrane,  brokenuterus, date,  diabetes,  dppni,  earlyplacenta,  fetuspain,  hypertension,  laceaccident,  ovularinfection,  polidependencia,  rciu,  rhsensibility,  risk, time,  vdrl,  weeksgestation,  createdby_rut,  deliverytype_id,  mother_id )
VALUES (37,  '', TRUE, TRUE,  '2010-06-22', TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE,  '05:16:34', TRUE, 33,  '164377377', 4, 37);
INSERT INTO delivery (id,  anotherpathologydescription,  brokenmembrane,  brokenuterus, date,  diabetes,  dppni,  earlyplacenta,  fetuspain,  hypertension,  laceaccident,  ovularinfection,  polidependencia,  rciu,  rhsensibility,  risk, time,  vdrl,  weeksgestation,  createdby_rut,  deliverytype_id,  mother_id )
VALUES (38,  '', TRUE, TRUE,  '2011-06-22', TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE,  '05:16:34', TRUE, 34,  '164377377', 2, 38);
INSERT INTO delivery (id,  anotherpathologydescription,  brokenmembrane,  brokenuterus, date,  diabetes,  dppni,  earlyplacenta,  fetuspain,  hypertension,  laceaccident,  ovularinfection,  polidependencia,  rciu,  rhsensibility,  risk, time,  vdrl,  weeksgestation,  createdby_rut,  deliverytype_id,  mother_id )
VALUES (39,  '', TRUE, TRUE,  '2012-06-22', TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE,  '05:16:34', TRUE, 35,  '164377377', 2, 39);
INSERT INTO delivery (id,  anotherpathologydescription,  brokenmembrane,  brokenuterus, date,  diabetes,  dppni,  earlyplacenta,  fetuspain,  hypertension,  laceaccident,  ovularinfection,  polidependencia,  rciu,  rhsensibility,  risk, time,  vdrl,  weeksgestation,  createdby_rut,  deliverytype_id,  mother_id )
VALUES (40,  '', TRUE, TRUE,  '2013-06-22', TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE,  '05:16:34', TRUE, 36,  '164377377', 1, 40);
INSERT INTO delivery (id,  anotherpathologydescription,  brokenmembrane,  brokenuterus, date,  diabetes,  dppni,  earlyplacenta,  fetuspain,  hypertension,  laceaccident,  ovularinfection,  polidependencia,  rciu,  rhsensibility,  risk, time,  vdrl,  weeksgestation,  createdby_rut,  deliverytype_id,  mother_id )
VALUES (41,  '', TRUE, TRUE,  '2014-06-22', TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE,  '05:16:34', TRUE, 37,  '164377377', 1, 41);
INSERT INTO delivery (id,  anotherpathologydescription,  brokenmembrane,  brokenuterus, date,  diabetes,  dppni,  earlyplacenta,  fetuspain,  hypertension,  laceaccident,  ovularinfection,  polidependencia,  rciu,  rhsensibility,  risk, time,  vdrl,  weeksgestation,  createdby_rut,  deliverytype_id,  mother_id )
VALUES (42,  '', TRUE, TRUE,  '2010-06-22', TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE,  '05:16:34', TRUE, 30,  '164377377', 3, 42);
INSERT INTO delivery (id,  anotherpathologydescription,  brokenmembrane,  brokenuterus, date,  diabetes,  dppni,  earlyplacenta,  fetuspain,  hypertension,  laceaccident,  ovularinfection,  polidependencia,  rciu,  rhsensibility,  risk, time,  vdrl,  weeksgestation,  createdby_rut,  deliverytype_id,  mother_id )
VALUES (43,  '', TRUE, TRUE,  '2011-06-22', TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE,  '05:16:34', TRUE, 31,  '164377377', 2, 43);
INSERT INTO delivery (id,  anotherpathologydescription,  brokenmembrane,  brokenuterus, date,  diabetes,  dppni,  earlyplacenta,  fetuspain,  hypertension,  laceaccident,  ovularinfection,  polidependencia,  rciu,  rhsensibility,  risk, time,  vdrl,  weeksgestation,  createdby_rut,  deliverytype_id,  mother_id )
VALUES (44,  '', TRUE, TRUE,  '2012-06-22', TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE,  '05:16:34', TRUE, 32,  '164377377', 4, 44);
INSERT INTO delivery (id,  anotherpathologydescription,  brokenmembrane,  brokenuterus, date,  diabetes,  dppni,  earlyplacenta,  fetuspain,  hypertension,  laceaccident,  ovularinfection,  polidependencia,  rciu,  rhsensibility,  risk, time,  vdrl,  weeksgestation,  createdby_rut,  deliverytype_id,  mother_id )
VALUES (45,  '', TRUE, TRUE,  '2013-06-22', TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE,  '05:16:34', TRUE, 33,  '164377377', 3, 45);
INSERT INTO delivery (id,  anotherpathologydescription,  brokenmembrane,  brokenuterus, date,  diabetes,  dppni,  earlyplacenta,  fetuspain,  hypertension,  laceaccident,  ovularinfection,  polidependencia,  rciu,  rhsensibility,  risk, time,  vdrl,  weeksgestation,  createdby_rut,  deliverytype_id,  mother_id )
VALUES (46,  '', TRUE, TRUE,  '2014-06-22', TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE,  '05:16:34', TRUE, 34,  '164377377', 2, 46);
INSERT INTO delivery (id,  anotherpathologydescription,  brokenmembrane,  brokenuterus, date,  diabetes,  dppni,  earlyplacenta,  fetuspain,  hypertension,  laceaccident,  ovularinfection,  polidependencia,  rciu,  rhsensibility,  risk, time,  vdrl,  weeksgestation,  createdby_rut,  deliverytype_id,  mother_id )
VALUES (47,  '', TRUE, TRUE,  '2010-06-22', TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE,  '05:16:34', TRUE, 35,  '164377377', 1, 47);
INSERT INTO delivery (id,  anotherpathologydescription,  brokenmembrane,  brokenuterus, date,  diabetes,  dppni,  earlyplacenta,  fetuspain,  hypertension,  laceaccident,  ovularinfection,  polidependencia,  rciu,  rhsensibility,  risk, time,  vdrl,  weeksgestation,  createdby_rut,  deliverytype_id,  mother_id )
VALUES (48,  '', TRUE, TRUE,  '2011-06-22', TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE,  '05:16:34', TRUE, 36,  '164377377', 2, 48);
INSERT INTO delivery (id,  anotherpathologydescription,  brokenmembrane,  brokenuterus, date,  diabetes,  dppni,  earlyplacenta,  fetuspain,  hypertension,  laceaccident,  ovularinfection,  polidependencia,  rciu,  rhsensibility,  risk, time,  vdrl,  weeksgestation,  createdby_rut,  deliverytype_id,  mother_id )
VALUES (49,  '', TRUE, TRUE,  '2012-06-22', TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE,  '05:16:34', TRUE, 37,  '164377377', 2, 49);
INSERT INTO delivery (id,  anotherpathologydescription,  brokenmembrane,  brokenuterus, date,  diabetes,  dppni,  earlyplacenta,  fetuspain,  hypertension,  laceaccident,  ovularinfection,  polidependencia,  rciu,  rhsensibility,  risk, time,  vdrl,  weeksgestation,  createdby_rut,  deliverytype_id,  mother_id )
VALUES (50,  '', TRUE, TRUE,  '2013-06-22', TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE,  '05:16:34', TRUE, 30,  '164377377', 3, 50);
INSERT INTO delivery (id,  anotherpathologydescription,  brokenmembrane,  brokenuterus, date,  diabetes,  dppni,  earlyplacenta,  fetuspain,  hypertension,  laceaccident,  ovularinfection,  polidependencia,  rciu,  rhsensibility,  risk, time,  vdrl,  weeksgestation,  createdby_rut,  deliverytype_id,  mother_id )
VALUES (51,  '', TRUE, TRUE,  '2014-06-22', TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE,  '05:16:34', TRUE, 31,  '164377377', 4, 51);